### ISSUE TITLE
AWSAccelerator-PrepareStack is in UPDATE_ROLLBACK_FAILED state and can not be updated

### ISSUE THREAD

**Issue by jacekhewko** [awslabs/landing-zone-accelerator-on-aws#134]
**Describe the bug**
Trying to add new account via `accounts-config.yaml` but getting below error in the pipeline:

```

AWSAccelerator-PrepareStack-285412123187-eu-west-2 | 0/10 | 9:25:58 AM | UPDATE_FAILED        | 
Custom::CreateControlTowerAccounts                 | 
CreateCTAccounts/Resource/Default (CreateCTAccounts3049A752) Received response status [FAILED]
from custom resource. Message returned: Account creation failed. Error: Accounts failed to enroll in
Control Tower. Check Service Catalog Console

```

Any ideas what is going on?

What may be important here, a bit earlier I tried to remove account by removing it from `accounts-config.yaml`, but got error that the state which I am trying to deploy is different than Control Tower. So I bring this account back into the config yaml and just added another one. But failing with this odd error with `Check Service Catalog Console`.

EDIT: Above was caused by wrong e-mail address used, so I corrected it, but unfortunately getting another error:

```
AWSAccelerator-PrepareStack-285412123187-eu-west-2 failed: Error [ValidationError]: 
Stack:arn:aws:cloudformation:eu-west-2:285412123187:stack/AWSAccelerator-PrepareStack-285412123187-eu-west-2/d71ea590-cfba-11ed-a68d-06ab5b813948
 is in UPDATE_ROLLBACK_FAILED state and can not be updated.

```

Looks like previous error has left `AWSAccelerator-PrepareStack` stack with `UPDATE_ROLLBACK_FAILED` status with below message:

```
Received response status [FAILED] from custom resource. Message returned: Account creation failed. Error: Accounts failed to enroll in Control Tower. Check Service Catalog Console Logs: /aws/lambda/AWSAccelerator-PrepareSta-CreateCTAccountsCreateCo-Uco4JMpKspry at Runtime._m [as handler] (/var/task/index.js:32:16757) at processTicksAndRejections (internal/process/task_queues.js:95:5) (RequestId: d9b9885a-2894-4389-bc64-2ca379974353)
```

When tried to re-run the stack again, it fails with below:

```
Received response status [FAILED] from custom resource. Message returned: ExecutionAlreadyExists: Execution Already Exists: 'arn:aws:states:eu-west-2:285412123187:execution:CreateCTAccountsCreateControlTowerAcccountsProviderwaiterstatemachi-r9itYeiJej2B:d9b9885a-2894-4389-bc64-2ca379974353' at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27) at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20) at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10) at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14) at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10) at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12) at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10 at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9) at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12) at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18) (RequestId: d9b9885a-2894-4389-bc64-2ca379974353)
```

How can I fix the stack, and thus fix my deployment?

Thanks

**Comment by awsclemj** [comment]
Hello @jacekhewko, and thank you for your interest in Landing Zone Accelerator!

I believe that this troubleshooting page in our documentation may help with the error you're encountering: https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/problem-account-enrollment-and-environment-validation-failures.html

Please let us know if following these steps resolves your issue. Thanks!

**Comment by jacekhewko** [comment]
That worked for me, thank you @awsclemj

**Comment by sunstonesecure-robert** [comment]
still seeing this on a new account creation
