### ISSUE TITLE
Bootstrap Pipeline Stage Failure

### ISSUE THREAD

**Issue by gambol99** [awslabs/landing-zone-accelerator-on-aws#170]
**Describe the bug**

Control Tower v3.0

We created a new account via  the `account-config.yaml` which caused an issue with Enrolment (probaby due to us trying to place in the 'Security' OU perhaps). This caused the `Prepare` stage in the pipeline to get into a UPDATE_FAILED_ROLLBACK. Looking into the cloudformation console we saw

```
Received response status [FAILED] from custom resource. Message returned: Account creation failed. Error: Accounts failed to enroll in Control Tower. Check Service Catalog Console Logs:
```

Issue https://github.com/awslabs/landing-zone-accelerator-on-aws/issues/134 appeared to be an exact copy, so we went the Service Catalog and click 'terminate' under the provisioned product. We then followed the instructions [here](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/problem-account-enrollment-and-environment-validation-failures.html) and was able to get the Prepare stage working now. 

On kicking off a new release we now getting the below in the `Bootstrap` stage 

```shell 


2023-06-08 22:00:09.759 \| info \| AWSAccelerator-AccountsStack-XXXXXXXXXX-us-east-1 \| Completed stack synthesis
--
163 | 2023-06-08 22:00:09.760 \| info \| app \| Stack in account XXXXXXXXXX and region eu-west-2 using CliCredentialSynthesizer
164 | 2023-06-08 22:00:09.840 \| info \| AWSAccelerator-OrganizationsStack-XXXXXXXXXXX-eu-west-2 \| Delegated Admin account for Identity Center is: 012140491173
165 | 2023-06-08 22:00:09.848 \| error \| app \| Cannot read properties of undefined (reading 'indexOf')
166 | 2023-06-08 22:00:09.848 \| error \| toolkit \| TypeError: Cannot read properties of undefined (reading 'indexOf')
167 | 2023-06-08 22:00:09.854 \| error \| accelerator \| Runtime Error
168 | /codebuild/output/src344/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/accelerator.ts:56
169 | throw new Error('Synthesis failed');
170 | ^
171 |  
172 | Error: Synthesis failed
173 | at process.<anonymous> (/codebuild/output/src344/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/accelerator.ts:41:9)
174 | at process.emit (node:events:525:35)
175 | at process.emit (node:domain:489:12)
176 | at process.emit.sharedData.processEmitHook.installedValue [as emit] (/codebuild/output/src344/src/s3/00/source/node_modules/@cspotcode/source-map-support/source-map-support.js:745:40)
177 | at process._fatalException (node:internal/process/execution:149:25)
178 | Subprocess exited with error 7
179 | error Command failed with exit code 1.
180 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

And now stuck in the position of unble to proceed. 

**To Reproduce**

Steps above ^

- [x] Version: v1.4.1
- [x] Region: eu-west-2
- [x] Was the solution modified from the version published on this repository? no
- [] If the answer to the previous question was yes, are the changes available on GitHub? NA
- [] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? NA
- [] Were there any errors in the CloudWatch Logs? 

**Screenshots**
NA

**Additional context**
NA

**Comment by gambol99** [comment]
So in the end it was a silly mistake,; `centralSecurityServices.securityHub.excludedRegions` was deleted from the confg ...  Quick question, at the moment we had a Makefile check in the repo

```shell
 check-configuration:
    @echo "--> Validating Configuration (against Accelerator release: ${AWSLABS_BRANCH})"
    @if [ ! -d "${AWSLABS_REPOSITORY}" ]; then \
      echo "--> Cloning the AWS Accelerator source code, release: ${AWSLABS_BRANCH}"; \
      git clone "${AWSLABS_SOURCE}"; \
      cd ${AWSLABS_REPOSITORY} && git checkout "release/${AWSLABS_BRANCH}"; \
      cd source && yarn install; \
    fi
    @cd ${AWSLABS_REPOSITORY}/source && yarn validate-config ${PWD}
```

Is there a better way of valdating the configuration? missing variables? .. on top of adding log lines in the exception to help narrow down the cause

**Comment by gambol99** [comment]
Also, being able to turn on debug logging in the pipeline would be helpful ..

**Comment by awsclemj** [comment]
Hello @gambol99 and thank you for reaching the Landing Zone Accelerator on AWS team!

The Makefile is a good strategy for running config validation. Another way to do it would be to run it locally before checking your configuration into a repo. We have those steps documented in [DEVELOPING.md](https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/main/DEVELOPING.md).

Regarding the root cause of this particular error, it appears that our static validation did not catch this error before the CDK app ran. As such, I will enter in a feature request on your behalf in order to capture this case by our config validator. 

Thank you for reporting the issue!
