### ISSUE TITLE
Error [ValidationError]: Unable to fetch parameters [/accelerator/network/vpc/Shared-Workloads/id] from parameter store for this account

### ISSUE THREAD

**Issue by FlemmingBehrend** [awslabs/landing-zone-accelerator-on-aws#180]
**Describe the bug**
When we add new accounts through the accounts-config.yaml we experience an error in the `Network_Associations` step. Here we get the following error message.

❌ AWSAccelerator-NetworkAssociationsStack-885652720545-eu-west-1 failed: Error [ValidationError]: Unable to fetch parameters [/accelerator/network/vpc/Shared-Workloads/id] from parameter store for this account.

at Request.extractError (/codebuild/output/src437/src/s3/00/source/node_modules/aws-sdk/lib/protocol/query.js:50:29)
at Request.callListeners (/codebuild/output/src437/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at Request.emit (/codebuild/output/src437/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
at Request.emit (/codebuild/output/src437/src/s3/00/source/node_modules/aws-sdk/lib/request.js:686:14)
at Request.transition (/codebuild/output/src437/src/s3/00/source/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/codebuild/output/src437/src/s3/00/source/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /codebuild/output/src437/src/s3/00/source/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request. (/codebuild/output/src437/src/s3/00/source/node_modules/aws-sdk/lib/request.js:38:9)
at Request. (/codebuild/output/src437/src/s3/00/source/node_modules/aws-sdk/lib/request.js:688:12)
at Request.callListeners (/codebuild/output/src437/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
code: 'ValidationError',
time: 2023-06-16T13:13:00.585Z,
requestId: 'e9fc6af1-b7fc-41d7-aff7-452b9a07f99c',
statusCode: 400,
retryable: false,
retryDelay: 606.7194975361567
}

**To Reproduce**
1. Install LZA with control tower
2. Add new account to `Workloads` OU

**Expected behavior**
I would have expected the pipeline to execute without errors

**Please complete the following information about the solution:**

- [ ] Version: [e.g. v1.4.1]

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0021) - Video On Demand workflow with AWS Step Functions, MediaConvert, MediaPackage, S3, CloudFront and DynamoDB. Version **v5.0.0**_". If the description does not contain the version information, you can look at the mappings section of the template:

```yaml
Mappings:
  SourceCode:
    General:
      S3Bucket: "solutions"
      KeyPrefix: "video-on-demand-on-aws/v5.0.0"
```

- [ ] Region: **[eu-west-1]**
- [ ] Was the solution modified from the version published on this repository? **No**
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? **Yes**
- [ ] Were there any errors in the CloudWatch Logs? **Unaware**

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**
We have tried to follow the advise from the issue https://github.com/awslabs/landing-zone-accelerator-on-aws/issues/177 but when we log in to the workloads account as root, we can not modify parameters in Parameter Store.

We get stopped by a service control policy and get the error that we do not have access to ssm:DescribeParameters

**Comment by erwaxler** [comment]
Hi @FlemmingBehrend , thank you for your patience on this issue. This behavior was fixed in our latest release v1.4.2, please update your LZA deployment to version 1.4.2 in order to resolve the behavior. I'll be closing this issue now that the fix has been released, thank you again for bringing this to our attention.
