### ISSUE TITLE
Cannot synthesize cloudformation template

### ISSUE THREAD

**Issue by sbussetti** [awslabs/landing-zone-accelerator-on-aws#24]
when running
`yarn cdk synth`
from within `source/packages/@aws-accelerator/installer` using node v18.12.1 (current LTS) I receive the following error:

```
yarn run v1.22.19
$ cdk synth
/Users/sbussetti/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
bin/installer.ts:16:22 - error TS2307: Cannot find module 'aws-cdk-lib' or its corresponding type declarations.

16 import * as cdk from 'aws-cdk-lib';
                        ~~~~~~~~~~~~~
bin/installer.ts:17:36 - error TS2307: Cannot find module 'cdk-nag' or its corresponding type declarations.

17 import { AwsSolutionsChecks } from 'cdk-nag';
                                      ~~~~~~~~~
bin/installer.ts:30:3 - error TS2584: Cannot find name 'console'. Do you need to change your target library? Try changing the 'lib' compiler option to include 'dom'.

30   console.log(`Invalid --management-cross-account-role-name ${managementCrossAccountRoleName}`);
     ~~~~~~~
bin/installer.ts:37:3 - error TS2345: Argument of type '{ description: string; synthesizer: any; useExternalPipelineAccount: boolean; enableTester: boolean; managementCrossAccountRoleName: any; }' is not assignable to parameter of type 'InstallerStackProps'.
  Object literal may only specify known properties, and 'description' does not exist in type 'InstallerStackProps'.

37   description: `(SO0199) Landing Zone Accelerator on AWS. Version ${version}.`,
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (/Users/sbussetti/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/Users/sbussetti/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/Users/sbussetti/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/Users/sbussetti/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/Users/sbussetti/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/sbussetti/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  diagnosticCodes: [ 2307, 2307, 2584, 2345 ]
}

Subprocess exited with error 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by joshbfei** [comment]
have you run 'npm install' prior to running your synth command?

**Comment by erwaxler** [comment]
@sbussetti any update on this? Otherwise I will be closing this as a local development environment issue.

**Comment by awsclemj** [comment]
I have created a backlog item to update our README to be more explicit about steps required to synthesize the installer template; we do not have `npm install` called out there. 

Closing this issue.
