### ISSUE TITLE
Unmanaging an account?

### ISSUE THREAD

**Issue by jacekhewko** [awslabs/landing-zone-accelerator-on-aws#250]
Hi,

At some point I decided to stop managing one of the accounts in LZA (as it was causing too many pipeline errors during deployments), so I removed it from accounts-config.yaml - and there was no other mentioning of this account in all the other config files. Unfortunately, this led to another pipeline error:

```

Logs: /aws/lambda/AWSAccelerator-PrepareSta-ValidateEnvironmentConfi-J1hHgo32KGMQ
--
268 |  
269 | at Runtime.CYr [as handler] (/var/task/index.js:89:240166)
270 | at processTicksAndRejections (node:internal/process/task_queues:96:5) (RequestId: 877d679b-2207-4c36-ace9-83cf933621f9)
271 | new CustomResource (/codebuild/output/src1622/src/s3/00/source/node_modules/aws-cdk-lib/core/lib/custom-resource.js:1:823)
272 | \_ new ValidateEnvironmentConfig (/codebuild/output/src1622/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/validate-environment-config.ts:138:22)
273 | \_ new PrepareStack (/codebuild/output/src1622/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/prepare-stack.ts:422:30)
274 | \_ main (/codebuild/output/src1622/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:487:28)
275 | \_ processTicksAndRejections (node:internal/process/task_queues:96:5)
276 | \_ async /codebuild/output/src1622/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:1017:5
277 |  
278 | ❌  AWSAccelerator-PrepareStack-285412123187-eu-west-2 failed: Error: The stack named AWSAccelerator-PrepareStack-285412123187-eu-west-2 failed to deploy: UPDATE_ROLLBACK_COMPLETE: Received response status [FAILED] from custom resource. Message returned: Account with Id xxxxxxxxxx and email xxx@xxx.xxx is not in the accounts configuration and is not a member of an ignored OU.
279 |  
280 | Logs: /aws/lambda/AWSAccelerator-PrepareSta-ValidateEnvironmentConfi-J1hHgo32KGMQ
281 |  
282 | at Runtime.CYr [as handler] (/var/task/index.js:89:240166)
283 | at processTicksAndRejections (node:internal/process/task_queues:96:5) (RequestId: 877d679b-2207-4c36-ace9-83cf933621f9)
284 | at FullCloudFormationDeployment.monitorDeployment (/codebuild/output/src1622/src/s3/00/source/node_modules/aws-cdk/lib/api/deploy-stack.ts:512:13)
285 | at processTicksAndRejections (node:internal/process/task_queues:96:5)
286 | at async deployStack (/codebuild/output/src1622/src/s3/00/source/node_modules/aws-cdk/lib/cdk-toolkit.ts:265:24)
287 | at async /codebuild/output/src1622/src/s3/00/source/node_modules/aws-cdk/lib/deploy.ts:39:11
288 | at async run (/codebuild/output/src1622/src/s3/00/source/node_modules/p-queue/dist/index.js:163:29)
289 |  
290 | ❌ Deployment failed: Error: Stack Deployments Failed: Error: The stack named AWSAccelerator-PrepareStack-285412123187-eu-west-2 failed to deploy: UPDATE_ROLLBACK_COMPLETE: Received response status [FAILED] from custom resource. Message returned: Account with Id xxxxxxxxxx and email xxx@xxx.xxx is not in the accounts configuration and is not a member of an ignored OU.
291 |  
292 | Logs: /aws/lambda/AWSAccelerator-PrepareSta-ValidateEnvironmentConfi-J1hHgo32KGMQ
293 |  
294 | at Runtime.CYr [as handler] (/var/task/index.js:89:240166)
295 | at processTicksAndRejections (node:internal/process/task_queues:96:5) (RequestId: 877d679b-2207-4c36-ace9-83cf933621f9)
296 | at deployStacks (/codebuild/output/src1622/src/s3/00/source/node_modules/aws-cdk/lib/deploy.ts:61:11)
297 | at processTicksAndRejections (node:internal/process/task_queues:96:5)
298 | at async CdkToolkit.deploy (/codebuild/output/src1622/src/s3/00/source/node_modules/aws-cdk/lib/cdk-toolkit.ts:339:7)
299 | at async Function.execute (/codebuild/output/src1622/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/toolkit.ts:312:9)
300 | at async /codebuild/output/src1622/src/s3/00/source/packages/@aws-accelerator/accelerator/cdk.ts:100:3
301 | 2023-09-01 05:57:41.406 \| error \| toolkit \| Stack Deployments Failed: Error: The stack named AWSAccelerator-PrepareStack-285412123187-eu-west-2 failed to deploy: UPDATE_ROLLBACK_COMPLETE: Received response status [FAILED] from custom resource. Message returned: Account with Id xxxxxxxxxx and email xxx@xxx.xxx is not in the accounts configuration and is not a member of an ignored OU.
302 |  
303 | Logs: /aws/lambda/AWSAccelerator-PrepareSta-ValidateEnvironmentConfi-J1hHgo32KGMQ
304 |  
305 | at Runtime.CYr [as handler] (/var/task/index.js:89:240166)
306 | at processTicksAndRejections (node:internal/process/task_queues:96:5) (RequestId: 877d679b-2207-4c36-ace9-83cf933621f9)
307 | Deployment failed
308 | error Command failed with exit code 1.
309 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
310 |  
311 | [Container] 2023/09/01 05:57:41 Command did not exit successfully yarn run ts-node --transpile-only cdk.ts --require-approval never $CDK_OPTIONS --config-dir $CODEBUILD_SRC_DIR_Config --partition aws --app cdk.out exit status 1
312 | [Container] 2023/09/01 05:57:41 Phase complete: BUILD State: FAILED
313 | [Container] 2023/09/01 05:57:41 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: yarn run ts-node --transpile-only cdk.ts --require-approval never $CDK_OPTIONS --config-dir $CODEBUILD_SRC_DIR_Config --partition aws --app cdk.out. Reason: exit status 1
314 | [Container] 2023/09/01 05:57:41 Entering phase POST_BUILD
315 | [Container] 2023/09/01 05:57:41 Phase complete: POST_BUILD State: SUCCEEDED
316 | [Container] 2023/09/01 05:57:41 Phase context status code:  Message:

```

Trying to fix this, I re-added the account to the configuration, but got below error:

```

AWSAccelerator-PrepareStack-xxxxxxxxxx-eu-west-2 failed: Error: The stack named AWSAccelerator-PrepareStack-xxxxxxxxxx-eu-west-2 failed to deploy: UPDATE_ROLLBACK_COMPLETE: Received response status [FAILED] from custom resource. Message returned: Account xxx@xxx.xx with account id xxxxxxxxxx is not in the correct OU. Account is in the ou named Root and should be in Workload,Account with Id xxxxxxxxxx and email xxx@xxx.xxx is not in the accounts configuration and is not a member of an ignored OU.

```

It persists even if I make 100% sure account-config.yaml describes the real setting, matching all OU names etc.

How can we fix it and what is the proper way of removing account from LZA management, then?

At the moment this account is unmanaged from the Control Tower and suspended and waiting for removal after 90 days, as it was empty test account and we don't need it anymore. But still I can'e see a way to unlock our pipeline failure, no matter if we include or exclude this account in the configuration.

Thanks,
Jacek

**Comment by awsclemj** [comment]
Hello,

You may follow the guidance [here](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/performing-administrator-tasks.html#closing-an-account) for unmanaging an account and ignoring the account from LZA resource provisioning.

I will mark this issue as resolved, but please feel free to write back if you have any follow-up questions.
