### ISSUE TITLE
v1.4.3 to v1.5.1 upgrade results in Operations Deployment failure

### ISSUE THREAD

**Issue by lucashalbert** [awslabs/landing-zone-accelerator-on-aws#293]
**Describe the bug**
After upgrading from LZA v1.4.3 to v1.5.0 and now 1.5.1, the `Operations` step in the `Deploy` stage fails while performing `sso:UpdatePermissionSet` using the `arn:aws:sts::012345678901:assumed-role/AWSControlTowerExecution/cdk-assume-role-plugin` role.

The assumed `AWSControlTowerExecution` role within the account that is failing (the Control Tower `Audit` account)  has the `AdministratorAccess` policy and no PermissionSets attached.

**Log Excerpt**
```
AWSAccelerator-OperationsStack-012345678901-us-east-1 |  5/27 | 5:42:21 PM | UPDATE_COMPLETE      | AWS::Logs::LogGroup          | Custom::SsmGetParameterValueCustomResourceProviderLogGroup (CustomSsmGetParameterValueCustomResourceProviderLogGroup780D220D) 
AWSAccelerator-OperationsStack-012345678901-us-east-1 |  6/27 | 5:42:21 PM | UPDATE_COMPLETE      | AWS::IAM::Role               | AssetAccessRole012345678901 (AssetAccessRole0123456789016C7363D4) 
AWSAccelerator-OperationsStack-012345678901-us-east-1 |  7/27 | 5:42:22 PM | UPDATE_COMPLETE      | AWS::IAM::Role               | ServiceCatalogPropagationRole (ServiceCatalogPropagationRole17EC5FCF) 
AWSAccelerator-OperationsStack-012345678901-us-east-1 |  7/27 | 5:42:22 PM | UPDATE_IN_PROGRESS   | Custom::SsmGetParameterValue | AssetsBucketKms/Lookup/Resource/Default (AssetsBucketKmsLookup24313A2E) 
AWSAccelerator-OperationsStack-012345678901-us-east-1 |  8/27 | 5:42:22 PM | UPDATE_COMPLETE      | AWS::IAM::Role               | StackSetExecutionRole (StackSetExecutionRole02DBF677) 
AWSAccelerator-OperationsStack-012345678901-us-east-1 |  9/27 | 5:42:23 PM | UPDATE_COMPLETE      | AWS::SSO::PermissionSet      | AdministratorAccessIdentityCenterPermissionSet 
AWSAccelerator-OperationsStack-012345678901-us-east-1 |  9/27 | 5:42:24 PM | UPDATE_IN_PROGRESS   | AWS::SSO::PermissionSet      | ReadOnlyAccessIdentityCenterPermissionSet 
AWSAccelerator-OperationsStack-012345678901-us-east-1 |  9/27 | 5:42:25 PM | UPDATE_FAILED        | AWS::SSO::PermissionSet      | ReadOnlyAccessIdentityCenterPermissionSet Resource handler returned message: "User: arn:aws:sts::012345678901:assumed-role/AWSControlTowerExecution/cdk-assume-role-plugin is not authorized to perform: sso:UpdatePermissionSet on resource: arn:aws:sso:::permissionSet/ssoins-obfuscatedID563e/ps-obfuscatedID77a4 (Service: SsoAdmin, Status Code: 400, Request ID: b0cd6fb2-37f1-4d20-af94-eda630a76579)" (RequestToken: 9f0a65e6-6664-4d21-9761-89c6ade22341, HandlerErrorCode: GeneralServiceException)
    OperationsStack.createPermissionsSet (/codebuild/output/src1719/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/operations-stack.ts:993:27)
    \_ OperationsStack.addIdentityCenterPermissionSets (/codebuild/output/src1719/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/operations-stack.ts:851:34)
    \_ OperationsStack.addIdentityCenterResources (/codebuild/output/src1719/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/operations-stack.ts:1122:40)
    \_ new OperationsStack (/codebuild/output/src1719/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/operations-stack.ts:134:12)
    \_ createOperationsStack (/codebuild/output/src1719/src/s3/00/source/packages/@aws-accelerator/accelerator/utils/stack-utils.ts:734:29)
    \_ createMultiAccountMultiRegionStacks (/codebuild/output/src1719/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:172:28)
    \_ main (/codebuild/output/src1719/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:232:5)
    \_ processTicksAndRejections (node:internal/process/task_queues:96:5)
    \_ async /codebuild/output/src1719/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:240:5
AWSAccelerator-OperationsStack-012345678901-us-east-1 |  9/27 | 5:42:25 PM | UPDATE_FAILED        | Custom::SsmGetParameterValue | AssetsBucketKms/Lookup/Resource/Default (AssetsBucketKmsLookup24313A2E) Resource update cancelled
    new CustomResource (/codebuild/output/src1719/src/s3/00/source/node_modules/aws-cdk-lib/core/lib/custom-resource.js:1:823)
    \_ new SsmParameterLookup (/codebuild/output/src1719/src/s3/00/source/packages/@aws-accelerator/constructs/lib/aws-ssm/ssm-parameter-lookup.ts:92:22)
    \_ new KeyLookup (/codebuild/output/src1719/src/s3/00/source/packages/@aws-accelerator/constructs/lib/aws-kms/key-lookup.ts:71:16)
    \_ OperationsStack.lookupAssetBucketKmsKey (/codebuild/output/src1719/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/operations-stack.ts:1179:14)
    \_ new OperationsStack (/codebuild/output/src1719/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/operations-stack.ts:120:36)
    \_ createOperationsStack (/codebuild/output/src1719/src/s3/00/source/packages/@aws-accelerator/accelerator/utils/stack-utils.ts:734:29)
    \_ createMultiAccountMultiRegionStacks (/codebuild/output/src1719/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:172:28)
    \_ main (/codebuild/output/src1719/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:232:5)
    \_ processTicksAndRejections (node:internal/process/task_queues:96:5)
    \_ async /codebuild/output/src1719/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:240:5
AWSAccelerator-OperationsStack-012345678901-us-east-1 |  9/27 | 5:42:26 PM | UPDATE_ROLLBACK_IN_P | AWS::CloudFormation::Stack   | AWSAccelerator-OperationsStack-012345678901-us-east-1 The following resource(s) failed to update: [ReadOnlyAccessIdentityCenterPermissionSet, AssetsBucketKmsLookup24313A2E].
AWSAccelerator-OperationsStack-012345678901-us-east-1 |  9/27 | 5:42:29 PM | UPDATE_IN_PROGRESS   | AWS::SSM::Parameter          | SsmParamAcceleratorVersion (SsmParamAcceleratorVersionFF83282D) 
AWSAccelerator-OperationsStack-012345678901-us-east-1 |  9/27 | 5:42:29 PM | UPDATE_IN_PROGRESS   | AWS::IAM::Role               | StackSetExecutionRole (StackSetExecutionRole02DBF677) 
AWSAccelerator-OperationsStack-012345678901-us-east-1 |  9/27 | 5:42:29 PM | UPDATE_IN_PROGRESS   | AWS::Lambda::Function        | Custom::SsmGetParameterValueCustomResourceProvider/Handler (CustomSsmGetParameterValueCustomResourceProviderHandlerAAD0E7EE) 
AWSAccelerator-OperationsStack-012345678901-us-east-1 |  9/27 | 5:42:29 PM | UPDATE_IN_PROGRESS   | AWS::IAM::Role               | AssetAccessRole012345678901 (AssetAccessRole0123456789016C7363D4) 
AWSAccelerator-OperationsStack-012345678901-us-east-1 |  9/27 | 5:42:29 PM | UPDATE_IN_PROGRESS   | AWS::IAM::Role               | ServiceCatalogPropagationRole (ServiceCatalogPropagationRole17EC5FCF) 
AWSAccelerator-OperationsStack-012345678901-us-east-1 |  9/27 | 5:42:29 PM | UPDATE_IN_PROGRESS   | AWS::SSM::Parameter          | SsmParamStackId (SsmParamStackId521A78D3) 
AWSAccelerator-OperationsStack-012345678901-us-east-1 |  8/27 | 5:42:29 PM | UPDATE_COMPLETE      | AWS::SSM::Parameter          | SsmParamAcceleratorVersion (SsmParamAcceleratorVersionFF83282D) 
AWSAccelerator-OperationsStack-012345678901-us-east-1 |  7/27 | 5:42:30 PM | UPDATE_COMPLETE      | AWS::SSM::Parameter          | SsmParamStackId (SsmParamStackId521A78D3) 
AWSAccelerator-OperationsStack-012345678901-us-east-1 |  8/27 | 5:42:31 PM | UPDATE_COMPLETE      | AWS::SSO::PermissionSet      | ReadOnlyAccessIdentityCenterPermissionSet 
AWSAccelerator-OperationsStack-012345678901-us-east-1 |  8/27 | 5:42:31 PM | UPDATE_IN_PROGRESS   | AWS::SSO::PermissionSet      | PortalProjectMerkleTeamIdentityCenterPermissionSet 
AWSAccelerator-OperationsStack-012345678901-us-east-1 |  8/27 | 5:42:32 PM | UPDATE_IN_PROGRESS   | AWS::SSO::PermissionSet      | AdministratorAccessIdentityCenterPermissionSet 
AWSAccelerator-OperationsStack-012345678901-us-east-1 |  7/27 | 5:42:39 PM | UPDATE_COMPLETE      | AWS::SSO::PermissionSet      | AdministratorAccessIdentityCenterPermissionSet 
AWSAccelerator-OperationsStack-012345678901-us-east-1 |  6/27 | 5:42:39 PM | UPDATE_COMPLETE      | AWS::SSO::PermissionSet      | PortalProjectMerkleTeamIdentityCenterPermissionSet 
AWSAccelerator-OperationsStack-012345678901-us-east-1 |  5/27 | 5:42:41 PM | UPDATE_COMPLETE      | AWS::Lambda::Function        | Custom::SsmGetParameterValueCustomResourceProvider/Handler (CustomSsmGetParameterValueCustomResourceProviderHandlerAAD0E7EE) 
AWSAccelerator-OperationsStack-012345678901-us-east-1 |  5/27 | 5:42:42 PM | UPDATE_IN_PROGRESS   | AWS::Logs::LogGroup          | Custom::SsmGetParameterValueCustomResourceProviderLogGroup (CustomSsmGetParameterValueCustomResourceProviderLogGroup780D220D) 
AWSAccelerator-OperationsStack-012345678901-us-east-1 |  4/27 | 5:42:43 PM | UPDATE_COMPLETE      | AWS::Logs::LogGroup          | Custom::SsmGetParameterValueCustomResourceProviderLogGroup (CustomSsmGetParameterValueCustomResourceProviderLogGroup780D220D) 
AWSAccelerator-OperationsStack-012345678901-us-east-1 |  4/27 | 5:42:43 PM | UPDATE_IN_PROGRESS   | Custom::SsmGetParameterValue | AssetsBucketKms/Lookup/Resource/Default (AssetsBucketKmsLookup24313A2E) 
AWSAccelerator-OperationsStack-012345678901-us-east-1 |  3/27 | 5:42:45 PM | UPDATE_COMPLETE      | AWS::IAM::Role               | AssetAccessRole012345678901 (AssetAccessRole0123456789016C7363D4) 
AWSAccelerator-OperationsStack-012345678901-us-east-1 |  2/27 | 5:42:45 PM | UPDATE_COMPLETE      | AWS::IAM::Role               | StackSetExecutionRole (StackSetExecutionRole02DBF677) 
AWSAccelerator-OperationsStack-012345678901-us-east-1 |  1/27 | 5:42:45 PM | UPDATE_COMPLETE      | AWS::IAM::Role               | ServiceCatalogPropagationRole (ServiceCatalogPropagationRole17EC5FCF) 
AWSAccelerator-OperationsStack-012345678901-us-east-1 |  2/27 | 5:42:50 PM | UPDATE_COMPLETE      | Custom::SsmGetParameterValue | AssetsBucketKms/Lookup/Resource/Default (AssetsBucketKmsLookup24313A2E) 
AWSAccelerator-OperationsStack-012345678901-us-east-1 |  3/27 | 5:42:51 PM | UPDATE_ROLLBACK_COMP | AWS::CloudFormation::Stack   | AWSAccelerator-OperationsStack-012345678901-us-east-1 
AWSAccelerator-OperationsStack-012345678901-us-east-1 |  4/27 | 5:42:51 PM | UPDATE_ROLLBACK_COMP | AWS::CloudFormation::Stack   | AWSAccelerator-OperationsStack-012345678901-us-east-1 

Failed resources:
AWSAccelerator-OperationsStack-012345678901-us-east-1 | 5:42:25 PM | UPDATE_FAILED        | AWS::SSO::PermissionSet      | ReadOnlyAccessIdentityCenterPermissionSet Resource handler returned message: "User: arn:aws:sts::012345678901:assumed-role/AWSControlTowerExecution/cdk-assume-role-plugin is not authorized to perform: sso:UpdatePermissionSet on resource: arn:aws:sso:::permissionSet/ssoins-obfuscatedID563e/ps-obfuscatedID77a4 (Service: SsoAdmin, Status Code: 400, Request ID: b0cd6fb2-37f1-4d20-af94-eda630a76579)" (RequestToken: 9f0a65e6-6664-4d21-9761-89c6ade22341, HandlerErrorCode: GeneralServiceException)
    OperationsStack.createPermissionsSet (/codebuild/output/src1719/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/operations-stack.ts:993:27)
    \_ OperationsStack.addIdentityCenterPermissionSets (/codebuild/output/src1719/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/operations-stack.ts:851:34)
    \_ OperationsStack.addIdentityCenterResources (/codebuild/output/src1719/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/operations-stack.ts:1122:40)
    \_ new OperationsStack (/codebuild/output/src1719/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/operations-stack.ts:134:12)
    \_ createOperationsStack (/codebuild/output/src1719/src/s3/00/source/packages/@aws-accelerator/accelerator/utils/stack-utils.ts:734:29)
    \_ createMultiAccountMultiRegionStacks (/codebuild/output/src1719/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:172:28)
    \_ main (/codebuild/output/src1719/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:232:5)
    \_ processTicksAndRejections (node:internal/process/task_queues:96:5)
    \_ async /codebuild/output/src1719/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:240:5

 ❌  AWSAccelerator-OperationsStack-012345678901-us-east-1 failed: Error: The stack named AWSAccelerator-OperationsStack-012345678901-us-east-1 failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "User: arn:aws:sts::012345678901:assumed-role/AWSControlTowerExecution/cdk-assume-role-plugin is not authorized to perform: sso:UpdatePermissionSet on resource: arn:aws:sso:::permissionSet/ssoins-obfuscatedID563e/ps-obfuscatedID77a4 (Service: SsoAdmin, Status Code: 400, Request ID: b0cd6fb2-37f1-4d20-af94-eda630a76579)" (RequestToken: 9f0a65e6-6664-4d21-9761-89c6ade22341, HandlerErrorCode: GeneralServiceException)
    at FullCloudFormationDeployment.monitorDeployment (/codebuild/output/src1719/src/s3/00/source/node_modules/aws-cdk/lib/api/deploy-stack.ts:512:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.deployStack (/codebuild/output/src1719/src/s3/00/source/node_modules/aws-cdk/lib/cdk-toolkit.ts:287:24)
    at async /codebuild/output/src1719/src/s3/00/source/node_modules/aws-cdk/lib/util/work-graph.ts:105:11

 ❌ Deployment failed: Error: The stack named AWSAccelerator-OperationsStack-012345678901-us-east-1 failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "User: arn:aws:sts::012345678901:assumed-role/AWSControlTowerExecution/cdk-assume-role-plugin is not authorized to perform: sso:UpdatePermissionSet on resource: arn:aws:sso:::permissionSet/ssoins-obfuscatedID563e/ps-obfuscatedID77a4 (Service: SsoAdmin, Status Code: 400, Request ID: b0cd6fb2-37f1-4d20-af94-eda630a76579)" (RequestToken: 9f0a65e6-6664-4d21-9761-89c6ade22341, HandlerErrorCode: GeneralServiceException)
    at FullCloudFormationDeployment.monitorDeployment (/codebuild/output/src1719/src/s3/00/source/node_modules/aws-cdk/lib/api/deploy-stack.ts:512:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.deployStack (/codebuild/output/src1719/src/s3/00/source/node_modules/aws-cdk/lib/cdk-toolkit.ts:287:24)
    at async /codebuild/output/src1719/src/s3/00/source/node_modules/aws-cdk/lib/util/work-graph.ts:105:11
2023-10-20 17:42:52.187 | error | toolkit | The stack named AWSAccelerator-OperationsStack-012345678901-us-east-1 failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "User: arn:aws:sts::012345678901:assumed-role/AWSControlTowerExecution/cdk-assume-role-plugin is not authorized to perform: sso:UpdatePermissionSet on resource: arn:aws:sso:::permissionSet/ssoins-obfuscatedID563e/ps-obfuscatedID77a4 (Service: SsoAdmin, Status Code: 400, Request ID: b0cd6fb2-37f1-4d20-af94-eda630a76579)" (RequestToken: 9f0a65e6-6664-4d21-9761-89c6ade22341, HandlerErrorCode: GeneralServiceException)
Deployment failed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[Container] 2023/10/20 17:42:52 Command did not exit successfully if [ "diff" != "${CDK_OPTIONS}" ]; then yarn run ts-node --transpile-only cdk.ts --require-approval never $CDK_OPTIONS --config-dir $CODEBUILD_SRC_DIR_Config --partition aws --app cdk.out; fi exit status 1
[Container] 2023/10/20 17:42:52 Phase complete: BUILD State: FAILED
[Container] 2023/10/20 17:42:52 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: if [ "diff" != "${CDK_OPTIONS}" ]; then yarn run ts-node --transpile-only cdk.ts --require-approval never $CDK_OPTIONS --config-dir $CODEBUILD_SRC_DIR_Config --partition aws --app cdk.out; fi. Reason: exit status 1
```

**To Reproduce**
Run the LZA Core Pipeline after upgrading from v1.4.3 to v1.5.0 or v1.5.1

**Expected behavior**
I expected the Core Pipeline to complete successfully like it did immediately prior to upgrading LZA.

**Please complete the following information about the solution:**

- [X] Version: [v1.5.1]

> To get the version of the solution, you can look at the description of the created AWS CloudFormation stack used to install the LZA (AWSAccelerator-InstallerStack). For example, "__(SO0199) Landing Zone Accelerator on AWS. **Version 1.5.1.**__". If the description does not contain the version information, you can look at the Parameters of the stack for the **RepositoryBranchName** as that should contain the version number.

- [X] Region: [us-east-1]
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [X] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).
![image](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/10239909/d5b6f46c-9c6f-41a0-a5f4-7ad1bb8c7e3f)

**Additional context**
The Core Pipeline was executed successfully before applying the v1.5.0 LZA upgrade. No other changes to the `Configuration` core pipeline source were made before or after the upgrade.

**Comment by richardkeit** [comment]
@lucashalbert - have you assigned this permission set in the `management` account?
If so, I believe this is an expected failure

**Comment by lucashalbert** [comment]
@richardkeit - that was it. Thank you for pointing it out! 🎉

**Comment by devalibvr** [comment]
@richardkeit @lucashalbert same error. as @carter-maclennan asked, Could you explain why this is an expected failure?

**Comment by felipempda** [comment]
@devalibvr @carter-maclennan 
I had the same problem. It's a limitation of the configuration when using delegated account: https://docs.aws.amazon.com/singlesignon/latest/userguide/troubleshooting.html?icmpid=docs_sso_console#issue15

```yaml
This message indicates that the [Delegated administration](https://docs.aws.amazon.com/singlesignon/latest/userguide/delegated-admin.html) feature has 
been enabled and that the operation you previously attempted 
can only be successfully performed by someone who has management account 
privileges in AWS Organizations. To resolve this issue, sign in as a user who has 
these privileges and try performing the task again or assign this task to someone who has the correct permissions. 
For more information, see [Register a member account](https://docs.aws.amazon.com/singlesignon/latest/userguide/delegated-admin.html#delegated-admin-how-to-register).
```

That probably means someone has manually added this permissionSet to the management account and it needs to be removed for the pipeline to work (somebody with access to the management account must do it).

How to do it:
https://stackoverflow.com/questions/75006646/how-to-remove-a-permission-set-for-a-user-in-iam-identity-center

```yaml
    Navigate to the IAM Identity Center console and under "Multi-Account Permissions" on the left hand side, select "AWS Accounts"
    Click on the desired account link, rather than the checkbox to the left.
    Once in the individual account, under the "Users and Groups" tabs, you would see the users and groups for this account.
    Select the radial button next to the username or group and click on the "Change Permission Sets" button towards the right side of the screen.
    From this page you can then uncheck the desired permission permission set and click "Save Changes".
```
