### ISSUE TITLE
Failing at Logging phase: S3 PutPublicAccessBlock access denied

### ISSUE THREAD

**Issue by jobalbz** [awslabs/landing-zone-accelerator-on-aws#319]
Looks like the SCP is blocking it.
<html>
<body>

LZADev-LoggingStack-12345678901-ca-central-1 \| 50/95 \| 7:21:38 PM \| CREATE_FAILED        \| Custom::PutPublicAccessBlock         \| S3PublicAccessBlock/Resource/Default (S3PublicAccessBlock344F906B) Received response status [FAILED] from custom resource. Message returned: AccessDenied: Access Denied

311 | at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_xml.js:53:29)
312 | at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
313 | at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
314 | at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)
315 | at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
316 | at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
317 | at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
318 | at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
319 | at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12)
320 | at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18) (RequestId: a3dfca11-5159-49a2-896b-4a9f2cca74c2)
321 | new CustomResource (/codebuild/output/src366/src/s3/00/source/node_modules/aws-cdk-lib/core/lib/custom-resource.js:1:823)
322 | \_ new S3PublicAccessBlock (/codebuild/output/src366/src/s3/00/source/packages/@aws-accelerator/constructs/lib/aws-s3/public-access-block.ts:62:22)
323 | \_ LoggingStack.configureS3PublicAccessBlock (/codebuild/output/src366/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/logging-stack.ts:618:31)
324 | \_ new LoggingStack (/codebuild/output/src366/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/logging-stack.ts:145:10)
325 | \_ createLoggingStack (/codebuild/output/src366/src/s3/00/source/packages/@aws-accelerator/accelerator/utils/stack-utils.ts:648:26)
326 | \_ createMultiAccountMultiRegionStacks (/codebuild/output/src366/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:166:25)
327 | \_ main (/codebuild/output/src366/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:232:5)
328 | \_ processTicksAndRejections (node:internal/process/task_queues:96:5)

</body>
</html>

**Comment by jobalbz** [comment]
Solution: Disabled the SCP manually
