### ISSUE TITLE
Action Execution Failed in Logging - Key stage

### ISSUE THREAD

**Issue by pieas-asif** [awslabs/landing-zone-accelerator-on-aws#342]
When executing Logging Stage **ChangeSet** AWSAccelerator-DependenciesStack-change-set cannot be created due to a mismatch with existing attribute **ClientToken**.

- [x] Version: [v1.5.2]

```
 ❌  AWSAccelerator-DependenciesStack-xxx-us-east-1 failed: AlreadyExistsException: ChangeSet AWSAccelerator-DependenciesStack-xxx-us-east-1-change-set cannot be created due to a mismatch with existing attribute ClientToken
    at Request.extractError (/codebuild/output/src3600/src/s3/00/source/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/codebuild/output/src3600/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/codebuild/output/src3600/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/codebuild/output/src3600/src/s3/00/source/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/codebuild/output/src3600/src/s3/00/source/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/codebuild/output/src3600/src/s3/00/source/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /codebuild/output/src3600/src/s3/00/source/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/codebuild/output/src3600/src/s3/00/source/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/codebuild/output/src3600/src/s3/00/source/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/codebuild/output/src3600/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'AlreadyExistsException',
  time: 2023-12-03T05:37:45.080Z,
  requestId: 'xxxxx',
  statusCode: 400,
  retryable: false,
  retryDelay: 885.8389794102081
}
```

![Screenshot from 2023-12-03 11-49-36](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/33780353/28a73df9-a320-4359-a8d1-5e92d6db39aa)

**Comment by k-hasan-19** [comment]
More context to the issue reported:
- We are trying to deploy [Landing Zone Accelerator on AWS for Healthcare](https://github.com/awslabs/landing-zone-accelerator-on-aws/tree/main/reference/sample-configurations/lza-sample-config-healthcare) for a client
- We got stuck at a code build step where CDK tries to create two changesets in parallel like below and fails with consecutive error
![image](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/6383136/8e7bd53e-96a4-4755-901e-89503c88bd03)

![image](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/6383136/b403ebb7-f111-43bf-b918-713c68a3c81f)

```bash
AWSAccelerator-KeyStack-053*****4157-us-east-1: creating CloudFormation changeset...
--
244 |  
245 | ❌  AWSAccelerator-DependenciesStack-053*****4157-us-east-1 failed: AlreadyExistsException: ChangeSet AWSAccelerator-DependenciesStack-053*****4157-us-east-1-change-set cannot be created due to a mismatch with existing attribute ClientToken
246 | at Request.extractError (/codebuild/output/src3600/src/s3/00/source/node_modules/aws-sdk/lib/protocol/query.js:50:29)
247 | at Request.callListeners (/codebuild/output/src3600/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
248 | at Request.emit (/codebuild/output/src3600/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
249 | at Request.emit (/codebuild/output/src3600/src/s3/00/source/node_modules/aws-sdk/lib/request.js:686:14)
250 | at Request.transition (/codebuild/output/src3600/src/s3/00/source/node_modules/aws-sdk/lib/request.js:22:10)
251 | at AcceptorStateMachine.runTo (/codebuild/output/src3600/src/s3/00/source/node_modules/aws-sdk/lib/state_machine.js:14:12)
252 | at /codebuild/output/src3600/src/s3/00/source/node_modules/aws-sdk/lib/state_machine.js:26:10
253 | at Request.<anonymous> (/codebuild/output/src3600/src/s3/00/source/node_modules/aws-sdk/lib/request.js:38:9)
254 | at Request.<anonymous> (/codebuild/output/src3600/src/s3/00/source/node_modules/aws-sdk/lib/request.js:688:12)
255 | at Request.callListeners (/codebuild/output/src3600/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
256 | code: 'AlreadyExistsException',
257 | time: 2023-12-03T05:37:45.080Z,
258 | requestId: 'ad95faca-a175-4d3a-88f8-b9eb1cbc26ab',
259 | statusCode: 400,
260 | retryable: false,
261 | retryDelay: 885.8389794102081
262 | }
263 |  
264 | ❌ Deployment failed: AlreadyExistsException: ChangeSet AWSAccelerator-DependenciesStack-053*****4157-us-east-1-change-set cannot be created due to a mismatch with existing attribute ClientToken
265 | at Request.extractError (/codebuild/output/src3600/src/s3/00/source/node_modules/aws-sdk/lib/protocol/query.js:50:29)
266 | at Request.callListeners (/codebuild/output/src3600/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
267 | at Request.emit (/codebuild/output/src3600/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
268 | at Request.emit (/codebuild/output/src3600/src/s3/00/source/node_modules/aws-sdk/lib/request.js:686:14)
269 | at Request.transition (/codebuild/output/src3600/src/s3/00/source/node_modules/aws-sdk/lib/request.js:22:10)
270 | at AcceptorStateMachine.runTo (/codebuild/output/src3600/src/s3/00/source/node_modules/aws-sdk/lib/state_machine.js:14:12)
271 | at /codebuild/output/src3600/src/s3/00/source/node_modules/aws-sdk/lib/state_machine.js:26:10
272 | at Request.<anonymous> (/codebuild/output/src3600/src/s3/00/source/node_modules/aws-sdk/lib/request.js:38:9)
273 | at Request.<anonymous> (/codebuild/output/src3600/src/s3/00/source/node_modules/aws-sdk/lib/request.js:688:12)
274 | at Request.callListeners (/codebuild/output/src3600/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
275 | code: 'AlreadyExistsException',
276 | time: 2023-12-03T05:37:45.080Z,
277 | requestId: 'ad95faca-a175-4d3a-88f8-b9eb1cbc26ab',
278 | statusCode: 400,
279 | retryable: false,
280 | retryDelay: 885.8389794102081
281 | }
282 | 2023-12-03 05:37:45.082 \| error \| toolkit \| ChangeSet AWSAccelerator-DependenciesStack-053*****4157-us-east-1-change-set cannot be created due to a mismatch with existing attribute ClientToken
283 | Deployment failed
284 | error Command failed with exit code 1.

```

**Comment by k-hasan-19** [comment]
@bhkhatri221 we are just trying to deploy the Landing Zone Accelerator on AWS for Healthcare and facing this issue
https://github.com/awslabs/landing-zone-accelerator-on-aws/tree/main/reference/sample-configurations/lza-sample-config-healthcare

**Comment by pieas-asif** [comment]
Hello @bhkhatri221, as per documentation and deployment instructions at [README.md](https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/main/reference/sample-configurations/lza-sample-config-healthcare/README.md), we followed the steps from 1 to 4. 
Step 1 to 3 was smooth without error. But during step 4 we are facing errors at CodePipeline. Specifically, we are getting error at Logging Key stage. 

The actual error message is 
`AWSAccelerator-KeyStack-053917174157-us-east-1 failed: AlreadyExistsException: ChangeSet AWSAccelerator-KeyStack-053917174157-us-east-1-change-set cannot be created due to a mismatch with existing attribute ClientToken`

We found that this error is caused by the [pipeline.ts](https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/main/source/packages/%40aws-accelerator/accelerator/lib/pipeline.ts) file in aws-accelerator/accelerator/lib/pipeline.ts in 427 line.

**Comment by hpf-mrnf** [comment]
We are also facing the same issue as described.
![image](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/132080444/e556a7e9-304f-4a89-8795-e01e8ff40b5f)
![image](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/132080444/618bbcca-b665-4ecb-8291-ab850bab8869)
