### ISSUE TITLE
Infrastructure-as-code drift with networking resources

### ISSUE THREAD

**Issue by richardkeit** [awslabs/landing-zone-accelerator-on-aws#345]
**Describe the bug**
Dependant resources in VPC should cause cloudformation update to fail, while re-running will cause IaC drift as Cloudformation stack says resources are removed but the resources are still present

**To Reproduce**
- Create a network in an account (example account `Testing-Workload`) , eg `network-config.yaml`:
~~~yaml
vpcs:
  - name: MyTestNetwork
    account: Testing-Workload
    region: ap-southeast-2
    cidrs:
      - 10.0.0.0/16
    enableDnsHostnames: true
    enableDnsSupport: true
    instanceTenancy: default
    internetGateway: true
    routeTables:
      - name: PublicRouteTable
        routes:
          - name: LocalRoute
            type: local
            destination: 10.0.0.0/16
          - name: IgwRoute
            destination: 0.0.0.0/0
            type: internetGateway
            target: IGW
      - name: PrivateRouteTable
        routes:
          - name: LocalRoute
            type: local
            destination: 10.0.0.0/16
          - name: NatRoute
            destination: 0.0.0.0/0
            type: natGateway
            target: accelerator-nat-gw
    subnets: 
      - name: public-subnet-a
        availabilityZone: a
        routeTable: PublicRouteTable
        ipv4CidrBlock: 10.0.0.0/24
        tags: 
          - key: Name
            value: public-subnet-a
      - name: public-subnet-b
        availabilityZone: b
        routeTable: PublicRouteTable
        ipv4CidrBlock: 10.0.1.0/24
        tags: 
          - key: Name
            value: public-subnet-b
      - name: public-subnet-c
        availabilityZone: c
        routeTable: PublicRouteTable
        ipv4CidrBlock: 10.0.2.0/24
        tags: 
          - key: Name
            value: public-subnet-c
      - name: private-subnet-a
        availabilityZone: a
        routeTable: PrivateRouteTable
        ipv4CidrBlock: 10.0.3.0/24
        tags: 
          - key: Name
            value: private-subnet-a
      - name: private-subnet-b
        availabilityZone: b
        routeTable: PrivateRouteTable
        ipv4CidrBlock: 10.0.4.0/24
        tags: 
          - key: Name
            value: private-subnet-b
      - name: private-subnet-c
        availabilityZone: c
        routeTable: PrivateRouteTable
        ipv4CidrBlock: 10.0.5.0/24
        tags: 
          - key: Name
            value: private-subnet-c
    natGateways: 
      - name: accelerator-nat-gw
        subnet: public-subnet-a
        tags: 
          - key: Name
            value: MyNatGateway
    transitGatewayAttachments: []
    tags: 
      - key: CreatedBy
        value: MyLzaAttempt
~~~
- Launch an EC2 instance in a subnet created
- Remove the VPC in the `network-config.yaml`, eg:
~~~yaml
vpcs: []
~~~
- Pipeline will fail with something similar to:
~~~bash
AWSAccelerator-NetworkVpcStack-1111111111-NOT-AN-AWS-REGION | 31/34 | 4:24:39 AM | DELETE_FAILED        | AWS::EC2::Subnet    | MyTestNetworkVpcPrivateSubnetASubnet9FA69B07 Resource handler returned message: "The subnet 'subnet-0e3daad21324774b0' has dependencies and cannot be deleted. (Service: Ec2, Status Code: 400, Request ID: b16a5f9f-8753-4616-8e49-b9a7e1133e4f)" (RequestToken: 7683c263-623d-3e72-1998-34d657a4ed03, HandlerErrorCode: InvalidRequest)
AWSAccelerator-NetworkVpcStack-1111111111-NOT-AN-AWS-REGION | 31/34 | 4:24:40 AM | DELETE_IN_PROGRESS   | AWS::EC2::VPC       | MyTestNetworkVpc15415B6D 
31/34 Currently in progress: AWSAccelerator-NetworkVpcStack-1111111111-NOT-AN-AWS-REGION, MyTestNetworkVpc15415B6D
AWSAccelerator-NetworkVpcStack-1111111111-NOT-AN-AWS-REGION | 31/34 | 4:40:43 AM | DELETE_FAILED        | AWS::EC2::VPC       | MyTestNetworkVpc15415B6D Resource handler returned message: "The vpc 'vpc-08c2a7a7842e30418' has dependencies and cannot be deleted. (Service: Ec2, Status Code: 400, Request ID: d6f4ba74-cb4e-402c-9410-22821065583e)" (RequestToken: ed1ed0e5-be18-59ca-2651-6365ef21d1e2, HandlerErrorCode: InvalidRequest)
31/34 Currently in progress: AWSAccelerator-NetworkVpcStack-1111111111-NOT-AN-AWS-REGION
~~~
- Rerun pipeline
- **UNEXPECTED BEHAVIOR** - pipeline completes successfully
   - Cloudformation stack AWSAccelerator-NetworkVpcStack-1111111111-NOT-AN-AWS-REGION has 2x resources: 
       -  SsmParamStackIdXXXXXX
       - SsmParamAcceleratorVersionXXXXXX
   - AWS Infra: 
      - vpc-08c2a7a7842e30418 still exists
      -  subnet-0e3daad21324774b0 still exists
   
   
**Expected behavior**
The VPC is unable to be deleted AND the pipeline continues to fail regardless of re-attempts
Cloudformation stack state is representative of the AWS infrastructure deployed

**Please complete the following information about the solution:**

- [x] Version: v1.5.2
- [x] Region: ap-southeast-2
- [ ] ~Was the solution modified from the version published on this repository?~
- [ ] ~If the answer to the previous question was yes, are the changes available on GitHub?~
- [ ] ~Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?~
- [ ] ~Were there any errors in the CloudWatch Logs?~

**Screenshots**
~~~bash
AWSAccelerator-NetworkVpcStack-11111111-NOT-AN-AWS-REGION | 31/34 | 4:58:51 AM | DELETE_FAILED        | AWS::EC2::Subnet    | MyTestNetworkVpcPrivateSubnetASubnet9FA69B07 Resource handler returned message: "The subnet 'subnet-0e3daad21324774b0' has dependencies and cannot be deleted. (Service: Ec2, Status Code: 400, Request ID: 1539f8d6-6127-493b-896d-05320273349a)" (RequestToken: 7c67077d-6f17-6409-ca14-1fbc9a2a8aab, HandlerErrorCode: InvalidRequest)
AWSAccelerator-NetworkVpcStack-11111111-NOT-AN-AWS-REGION | 31/34 | 4:58:52 AM | DELETE_IN_PROGRESS   | AWS::EC2::VPC       | MyTestNetworkVpc15415B6D 
31/34 Currently in progress: AWSAccelerator-NetworkVpcStack-11111111-ap-southeast-2, MyTestNetworkVpc15415B6D
Error occurred while monitoring stack: ExpiredToken: The security token included in the request is expired
    at Request.extractError (/codebuild/output/src1151/src/s3/00/source/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/codebuild/output/src1151/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/codebuild/output/src1151/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/codebuild/output/src1151/src/s3/00/source/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/codebuild/output/src1151/src/s3/00/source/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/codebuild/output/src1151/src/s3/00/source/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /codebuild/output/src1151/src/s3/00/source/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/codebuild/output/src1151/src/s3/00/source/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/codebuild/output/src1151/src/s3/00/source/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/codebuild/output/src1151/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ExpiredToken',
  time: 2023-12-05T05:15:36.109Z,
  requestId: 'f257d68a-6c76-4351-aefd-533e8a49264e',
  statusCode: 403,
  retryable: true
}
....<REMOVED FOR BREVITY>....
2023-12-05 05:25:19.594 | error | toolkit | The security token included in the request is expired
Deployment failed
~~~
<img width="1869" alt="image" src="https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/17537115/65f92546-a7bc-402d-a8ac-5928ea5588d0">

Rerun of codebuild stage:
~~~bash

✅  AWSAccelerator-NetworkVpcStack-11111111-NOT-AN-AWS-REGION (no changes)
--
225 |  
226 | ✨  Deployment time: 0.95s


~~~

**Additional context**

**Comment by fdjahnke** [comment]
Hello @richardkeit, thanks for filing this!

The behavior is inherent to CloudFormation, not something the accelerator can change. When you remove the VPC from network-config.yaml, CloudFormation tries to delete the subnet and VPC, but they have dependencies (your out-of-band EC2 instance) and can't be deleted. Per Monitor the progress of a stack update, CloudFormation makes three deletion attempts, then "removes the old resource from the stack and continues updating" — and the docs note this "is also true for resources that you have removed from the stack template." So the stack reaches UPDATE_COMPLETE, keeps only the two SSM parameters, and the VPC/subnet remain in the account, producing the drift.

The ExpiredToken is a separate, transient symptom: the long delete attempt outlived the session credentials, so the deploy errored out even though CloudFormation finished the update server-side. That's why the rerun shows "no changes."

Since the update completes as UPDATE_COMPLETE, the pipeline can't keep failing on reruns. To avoid the drift, terminate the EC2 instance and any ENIs in the subnet before removing the VPC from config — resources created outside LZA aren't tracked by the accelerator's stacks, so it can't clean them up for you.

Closing as expected CloudFormation behavior. If you'd like LZA to surface this kind of drift proactively, a separate feature request would be welcome. Feel free to ping me here with any follow-ups.
