### ISSUE TITLE
AWSAccelerator-OrganizationStack: AuditManagerEnableOrganizationAdminAccount Error

### ISSUE THREAD

**Issue by adeolaolawuyi** [awslabs/landing-zone-accelerator-on-aws#370]
**Describe the bug**
Deploying AWS LZA using AWS Organizations with a pre-existing CodeCommit repository, the OrganizationStack is failing when attempting to execute AuditManagerEnableOrganizationAdminAccount. The failure is due to the following reason:

`AWSAccelerator-OrganizationsStack-111111111111-eu-west-2 | 43/63 | 2:16:11 PM | CREATE_FAILED | Custom::AuditManagerEnableOrganizationAdminAccount | AuditManagerEnableOrganizationAdminAccount/Resource/Default (AuditManagerEnableOrganizationAdminAccount9070BCC2) Received response status [FAILED] from custom resource. Message returned: ValidationException: AWS Organizations can't complete your request because it conflicts with another attempt to modify the same entity. Try again later. (Service: AWSOrganizations; Status Code: 400; Error Code: ConcurrentModificationException; Request ID: fc1f4036-e407-4d69-bad2-e4a0a538abca; Proxy: null)
`

`Received response status [FAILED] from custom resource. Message returned: ValidationException: AWS Organizations can't complete your request because it conflicts with another attempt to modify the same entity. Try again later. (Service: AWSOrganizations; Status Code: 400; Error Code: ConcurrentModificationException; Request ID: fc1f4036-e407-4d69-bad2-e4a0a538abca; Proxy: null) at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:61:27) at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:61:8) at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20) at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10) at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14) at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10) at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12) at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10 at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9) at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12) (RequestId: fff87462-785f-466e-9ff8-71084b4b6fa3) `

Retrying the Organization Pipeline stage after manually deleting the OrganizationStack gave another error:

`AWSAccelerator-OrganizationsStack-111111111111-eu-west-2 | 38/63 | 3:43:13 PM | CREATE_FAILED | Custom::AuditManagerEnableOrganizationAdminAccount | AuditManagerEnableOrganizationAdminAccount/Resource/Default (AuditManagerEnableOrganizationAdminAccount9070BCC2) Received response status [FAILED] from custom resource. Message returned: ValidationException: Cannot change delegated Admin for an active account 111111111111 from null to [AuditAccountID]
`

`Received response status [FAILED] from custom resource. Message returned: ValidationException: Cannot change delegated Admin for an active account 111111111111 from null to [AuditAccountID] at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:61:27) at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:61:8) at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20) at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10) at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14) at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10) at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12) at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10 at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9) at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12) (RequestId: cca345ab-90c2-4979-b9b5-745dacb14ee2) `

**To Reproduce**
Deploy AWS LZA using AWS Organizations with a pre-existing codecommit repository. It's important to clarify that our setup does not involve AWS Control Tower.

**Expected behavior**
Pipeline to run successfully with no errors.

**Please complete the following information about the solution:**

- [ ] Version: v1.5.2
- [ ] Region: eu-west-2
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? Yes
- [ ] Were there any errors in the CloudWatch Logs? No

**Screenshots**
Screenshot attached.

**Additional context**
N/A
![Screenshot from 2024-01-02 14-34-29](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/115548896/ab02d7db-6f52-47e1-bb36-36f9147c974d)
![Screenshot from 2024-01-02 14-36-04](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/115548896/5d310717-1433-470f-9ca9-de0355fe33aa)
![Screenshot from 2024-01-02 15-32-02](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/115548896/b77db221-6b75-440d-b05b-e6a855ac35ef)
![Screenshot from 2024-01-02 15-33-07](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/115548896/56277d1e-3fbf-4642-85a5-703c587095ab)

**Comment by fdjahnke** [comment]
Hello @adeolaolawuyi, thank you for filing this issue with the Landing Zone Accelerator team!

This was addressed in **v1.15.0**. The AuditManager organization-admin custom resource was reworked so that AWS Organizations `ConcurrentModificationException` errors are automatically retried with backoff, and the handler now checks the current delegated-admin status and deregisters any existing admin before registering the new one — which resolves both the concurrent-modification failure and the follow-up "Cannot change delegated Admin ... from null" error you hit on re-run.

You're currently on **v1.5.2**. Please upgrade to the latest release (**v1.15.5**) by following [Update the solution](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/update-the-solution.html); that will pick up this fix along with many others.

Closing this as resolved — please feel free to follow up and ping me if you still see the error after upgrading.
