### ISSUE TITLE
can't add customer managed policy to role using iam-config.yaml

### ISSUE THREAD

**Issue by davidmulligan1** [awslabs/landing-zone-accelerator-on-aws#373]
**Describe the bug**
I can't add customer managed policy to role using iam-config.yaml

**To Reproduce**
I'm attempting to add a role with a customer created policy using the following code:

providers: []

policySets:
  - deploymentTargets:
     organizationalUnits:
       - Root
   policies:
     - name: DevPlusLocalTerraform
       policy: iam-policies/DevPlusLocalTerraform.json
roleSets:
  - deploymentTargets:
     organizationalUnits:
      - UAT
      - PROD
    roles:
      - name: AzureDevOpsDeployer_v1
        assumedBy:
          - type: account
            principal: "arn:aws:iam::***:root"
         policies:
           customerManaged:
             - arn:aws:iam::*:policy/DevPlusLocalTerraform

getting error: 

**Expected behavior**
Im expecting this to add this policy with the appropriate role

**Please complete the following information about the solution:**

- [ ] Version: . v1.5.1

- [ ] Region:  eu-west-1
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? yes
- [ ] Were there any errors in the CloudWatch Logs? yes:
<html>
<body>

024-01-11 13:35:11.055 \| error \| accelerator \| Resolution error: Resolution error: Resolution error: Cannot read properties of undefined (reading 'managedPolicyArn').
--
119 | Object creation stack:
120 | at new UniqueStringSet (/codebuild/output/src3854/src/s3/00/source/node_modules/aws-cdk-lib/aws-iam/lib/private/util.js:1:2060)
121 | at Function.from (/codebuild/output/src3854/src/s3/00/source/node_modules/aws-cdk-lib/aws-iam/lib/private/util.js:1:1961)
122 | at new Role (/codebuild/output/src3854/src/s3/00/source/node_modules/aws-cdk-lib/aws-iam/lib/role.js:1:5927)
123 | at OperationsStack.createRole (/codebuild/output/src3854/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/operations-stack.ts:422:18)
124 | at OperationsStack.addRoles (/codebuild/output/src3854/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/operations-stack.ts:464:27)
125 | at new OperationsStack (/codebuild/output/src3854/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/operations-stack.ts:128:12)
126 | at createOperationsStack (/codebuild/output/src3854/src/s3/00/source/packages/@aws-accelerator/accelerator/utils/stack-utils.ts:734:29)
127 | at createMultiAccountMultiRegionStacks (/codebuild/output/src3854/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:172:28)
128 | at main (/codebuild/output/src3854/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:232:5)
129 | at processTicksAndRejections (node:internal/process/task_queues:96:5)
130 | at async /codebuild/output/src3854/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:240:5..
131 | /codebuild/output/src3854/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/accelerator.ts:57
132 | throw new Error('Synthesis failed');
133 | ^
134 |  
135 | Error: Synthesis failed
136 | at process.<anonymous> (/codebuild/output/src3854/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/accelerator.ts:41:9)
137 | at process.emit (node:events:525:35)
138 | at process.emit (node:domain:489:12)
139 | at process.emit.sharedData.processEmitHook.installedValue [as emit] (/codebuild/output/src3854/src/s3/00/source/node_modules/@cspotcode/source-map-support/source-map-support.js:745:40)
140 | at process._fatalException (node:internal/process/execution:149:25)
141 | 2024-01-11 13:35:11.160 \| error \| toolkit \| Subprocess exited with error 7
142 | 2024-01-11 13:35:11.161 \| error \| toolkit \| Options were: {"command":"synth","enableSingleAccountMode":false,"partition":"aws","stackPrefix":"AWSAccelerator","stage":"operations","configDirPath":"/codebuild/output/src3854/src/s3/01","requireApproval":"never","cdkOptions":{"centralizeBuckets":true,"useManagementAccessRole":true},"useExistingRoles":false}
143 | Synthesis of stacks failed

</body>
</html>
**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**
what i'm trying to do here is to create this role in all new accounts automatically so it is easier to integrate with Azure DevOps
the role creates without attaching the policy

thanks for your help
David

**Comment by davidmulligan1** [comment]
just tried using the following and worked:

customerManaged:
   - DevPlusLocalTerraform
