### ISSUE TITLE
ValidateEnvironmentConfigValidateEnvironmentResourceD10DC179- Received response status [FAILED] from custom resource

### ISSUE THREAD

**Issue by durgasidileep** [awslabs/landing-zone-accelerator-on-aws#384]
**Describe the bug**
<html>
<body>

AWSAccelerator-PrepareStack-XXXXXXX-us-east-1 \|  55/102 \| 10:23:48 AM \| CREATE_FAILED        \| Custom::ValidateEnvironmentConfiguration           \| ValidateEnvironmentConfig/ValidateEnvironmentResource/Default (ValidateEnvironmentConfigValidateEnvironmentResourceD10DC179) Received response status [FAILED] from custom resource. Message returned: Organizational Unit 'Sandbox' with id of 'XXXXX' was not found in the organization configuration.,Organizational Unit 'SMB' with id of 'XXXXX' was not found in the organization configuration.
--
307 |  
308 | Logs: /aws/lambda/AWSAccelerator-PrepareSta-ValidateEnvironmentConfi-DuZJRi5dOx6O
309 |  
310 | at Runtime.Xur [as handler] (/var/task/index.js:10296:320469)
311 | at processTicksAndRejections (node:internal/process/task_queues:96:5) (RequestId: d0f73b34-f356-4e60-8da3-1f31d3a1cf98)
312 | new CustomResource (/codebuild/output/src3707/src/s3/00/source/node_modules/aws-cdk-lib/core/lib/custom-resource.js:1:823)
313 | \_ new ValidateEnvironmentConfig (/codebuild/output/src3707/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/validate-environment-config.ts:138:22)
314 | \_ PrepareStack.createConfigurationTables (/codebuild/output/src3707/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/prepare-stack.ts:407:26)
315 | \_ new PrepareStack (/codebuild/output/src3707/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/prepare-stack.ts:287:14)
316 | \_ createPrepareStack (/codebuild/output/src3707/src/s3/00/source/packages/@aws-accelerator/accelerator/utils/stack-utils.ts:381:26)
317 | \_ createManagementAccountStacks (/codebuild/output/src3707/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:100:21)
318 | \_ main (/codebuild/output/src3707/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:237:5)
319 | \_ processTicksAndRejections (node:internal/process/task_queues:96:5)
320 | \_ async /codebuild/output/src3707/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:251:5
321 | AWSAccelerator-PrepareStack-XXXXXX-us-east-1 \|  55/102 \| 10:23:49 AM \| CREATE_FAILED        \| Custom::CreateOrganizationalUnits                  \| CreateOrganizationalUnits/Resource/Default (CreateOrganizationalUnits3A58A65B) Resource creation cancelled
322 | new CustomResource (/codebuild/output/src3707/src/s3/00/source/node_modules/aws-cdk-lib/core/lib/custom-resource.js:1:823)
323 | \_ new OrganizationalUnits (/codebuild/output/src3707/src/s3/00/source/packages/@aws-accelerator/constructs/lib/aws-organizations/organizational-units.ts:75:22)
324 | \_ new PrepareStack (/codebuild/output/src3707/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/prepare-stack.ts:206:43)
325 | \_ createPrepareStack (/codebuild/output/src3707/src/s3/00/source/packages/@aws-accelerator/accelerator/utils/stack-utils.ts:381:26)
326 | \_ createManagementAccountStacks (/codebuild/output/src3707/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:100:21)
327 | \_ main (/codebuild/output/src3707/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:237:5)
328 | \_ processTicksAndRejections (node:internal/process/task_queues:96:5)

</body>
</html>

**To Reproduce**
1. We have initiated re-registration of Sandbox
2.  We have deleted and re-created Sandbox and re-registered to AWS Organization

**Expected behavior**

**Please complete the following information about the solution:**

- [ ] Version: [e.g. v1.5.1]

> To get the version of the solution, you can look at the description of the created AWS CloudFormation stack used to install the LZA (AWSAccelerator-InstallerStack). For example, "__(SO0199) Landing Zone Accelerator on AWS. **Version 1.5.1.**__". If the description does not contain the version information, you can look at the Parameters of the stack for the **RepositoryBranchName** as that should contain the version number.

- [ X] Region: [e.g. us-east-1]
- [No ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ Yes] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [No ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by bo1984** [comment]
Hi @durgasidileep! Thank you for using the Landing Zone Accelerator on AWS solution. By default AWS Control Tower will create the Sandbox OU (unless otherwise specified). In our [documentation](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/prerequisites.html#activate-a-multi-account-management-solution), we do require the use of the `Infrastructure` OU as I believe this is the leading cause of your issue. Can you please confirm if the Infrastructure OU exists in your Organization and is enrolled in Control Tower?

**Comment by durgasidileep** [comment]
We have Infrastructure OU created and it has been registered as well.  To reproduce the issue, we have deleted the existing Sandbox OU and re-created and registered to the organization , but we still encounter the above stated issue. You support is really appreciated.

**Comment by bo1984** [comment]
We keep metadata on your Organization which includes the Accounts and OUs, along with their respective IDs. In the DynamoDB table which would be named `AWSAccelerator-PrepareStack-[ACCOUNT ID]-[REGION]-AcceleratorConfigTable` in your Management account, we store this metadata. I suspect that the OUs in question exist in that table, but still have the old ID. Can you validate if that's the case by looking at the items. If the old IDs are in place, just remove the item from the table then retry the `Prepare` stage.

**Comment by durgasidileep** [comment]
I was trying to re-produce the issue by running failed pipeline and parallelly monitoring DynamoDB tables, while pipeline is running running the DynamoDB tables are getting created ( I am attaching the screenshots for the reference) , the moment the pipeline is failing, it's rolling back all the applied changes and DynamoDB tables are getting deleted and the pipeline is failing with same errors. I can't see any tables existing on the DynamoDB. 
![Dynamodb](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/68176805/2c9db9a0-7edb-4e7e-9be6-a09dade3a6b6)
![Dynamodb1](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/68176805/379d5eba-56de-41e2-b49e-1d83885fe4d2)
![Dynamodb2](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/68176805/0962240f-da61-4cd3-9a08-32e74e01f4a1)

Error:

AWSAccelerator-PrepareStack-XXXXXXXXX-us-east-1 |  55/102 | 5:25:13 AM | CREATE_IN_PROGRESS   | Custom::ValidateEnvironmentConfiguration           | ValidateEnvironmentConfig/ValidateEnvironmentResource/Default (ValidateEnvironmentConfigValidateEnvironmentResourceD10DC179) Resource creation Initiated
AWSAccelerator-PrepareStack-XXXXXXXXX-us-east-1 |  55/102 | 5:25:13 AM | CREATE_FAILED        | Custom::ValidateEnvironmentConfiguration           | ValidateEnvironmentConfig/ValidateEnvironmentResource/Default (ValidateEnvironmentConfigValidateEnvironmentResourceD10DC179) Received response status [FAILED] from custom resource. Message returned: Organizational Unit 'Sandbox' with id of 'ou-lpnw-eouydj0w' was not found in the organization configuration.,Organizational Unit 'SMB' with id of 'ou-lpnw-467gcjhe' was not found in the organization configuration.

Logs: /aws/lambda/AWSAccelerator-PrepareSta-ValidateEnvironmentConfi-ttCVHXuYI6lb

    at Runtime.Xur [as handler] (/var/task/index.js:10296:320469)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) (RequestId: 997293f6-35c1-4a63-b916-5d6a5a55bee1)
    new CustomResource (/codebuild/output/src1735/src/s3/00/source/node_modules/aws-cdk-lib/core/lib/custom-resource.js:1:823)
    \_ new ValidateEnvironmentConfig (/codebuild/output/src1735/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/validate-environment-config.ts:138:22)
    \_ PrepareStack.createConfigurationTables (/codebuild/output/src1735/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/prepare-stack.ts:407:26)
    \_ new PrepareStack (/codebuild/output/src1735/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/prepare-stack.ts:287:14)
    \_ createPrepareStack (/codebuild/output/src1735/src/s3/00/source/packages/@aws-accelerator/accelerator/utils/stack-utils.ts:381:26)
    \_ createManagementAccountStacks (/codebuild/output/src1735/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:100:21)
    \_ main (/codebuild/output/src1735/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:237:5)
    \_ processTicksAndRejections (node:internal/process/task_queues:96:5)
    \_ async /codebuild/output/src1735/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:251:5
AWSAccelerator-PrepareStack-XXXXXXXXX-us-east-1 |  55/102 | 5:25:13 AM | CREATE_FAILED        | Custom::CreateOrganizationalUnits                  | CreateOrganizationalUnits/Resource/Default (CreateOrganizationalUnits3A58A65B) Resource creation cancelled
    new CustomResource (/codebuild/output/src1735/src/s3/00/source/node_modules/aws-cdk-lib/core/lib/custom-resource.js:1:823)
    \_ new OrganizationalUnits (/codebuild/output/src1735/src/s3/00/source/packages/@aws-accelerator/constructs/lib/aws-organizations/organizational-units.ts:75:22)
    \_ new PrepareStack (/codebuild/output/src1735/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/prepare-stack.ts:206:43)
    \_ createPrepareStack (/codebuild/output/src1735/src/s3/00/source/packages/@aws-accelerator/accelerator/utils/stack-utils.ts:381:26)
    \_ createManagementAccountStacks (/codebuild/output/src1735/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:100:21)
    \_ main (/codebuild/output/src1735/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:237:5)
    \_ processTicksAndRejections (node:internal/process/task_queues:96:5)
    \_ async /codebuild/output/src1735/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:251:5
AWSAccelerator-PrepareStack-XXXXXXXXX-us-east-1 |  55/102 | 5:25:13 AM | CREATE_FAILED        | AWS::Events::Rule                                  | ControlTowerOuEventsRule (ControlTowerOuEventsRule7E8DCB15) Resource creation cancelled
    new Rule (/codebuild/output/src1735/src/s3/00/source/node_modules/aws-cdk-lib/aws-events/lib/rule.js:1:1368)
    \_ PrepareStack.createConfigurationTables (/codebuild/output/src1735/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/prepare-stack.ts:575:42)
    \_ new PrepareStack (/codebuild/output/src1735/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/stacks/prepare-stack.ts:287:14)
    \_ createPrepareStack (/codebuild/output/src1735/src/s3/00/source/packages/@aws-accelerator/accelerator/utils/stack-utils.ts:381:26)
    \_ createManagementAccountStacks (/codebuild/output/src1735/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:100:21)
    \_ main (/codebuild/output/src1735/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:237:5)
    \_ processTicksAndRejections (node:internal/process/task_queues:96:5)
    \_ async /codebuild/output/src1735/src/s3/00/source/packages/@aws-accelerator/accelerator/bin/app.ts:251:5
AWSAccelerator-PrepareStack-XXXXXXXXX-us-east-1 |  55/102 | 5:25:15 AM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack                         | AWSAccelerator-PrepareStack-XXXXXXXXX-us-east-1 The following resource(s) failed to create: [ControlTowerOuEventsRule7E8DCB15, CreateOrganizationalUnits3A58A65B, ValidateEnvironmentConfigValidateEnvironmentResourceD10DC179]. Rollback requested by user.
AWSAccelerator-PrepareStack-XXXXXXXXX-us-east-1 |  55/102 | 5:25:19 AM | DELETE_IN_PROGRESS   | AWS::KMS::Alias                                    | AcceleratorManagementCloudWatchKey/Alias (AcceleratorManagementCloudWatchKeyAliasF9F153C3)

**Comment by durgasidileep** [comment]
do you have any inputs on this?

**Comment by andreprawira** [comment]
@erwaxler any update on this? we are getting the same error, the dynamodb tables got created but eventually got reverted back from the failed stack, we tried this in v1.10.0 and v1.9.2 but both versions are giving us the same error. we tried deploying lza in different account and it worked with no error

**Comment by richardkeit** [comment]
Hey @andreprawira ,

Have you reviewed this note? 
I've had this issue over 1 year ago and this was the resolution

> We keep metadata on your Organization which includes the Accounts and OUs, along with their respective IDs. In the DynamoDB table which would be named `AWSAccelerator-PrepareStack-[ACCOUNT ID]-[REGION]-AcceleratorConfigTable` in your Management account, we store this metadata. I suspect that the OUs in question exist in that table, but still have the old ID. Can you validate if that's the case by looking at the items. If the old IDs are in place, just remove the item from the table then retry the `Prepare` stage.

**Comment by andreprawira** [comment]
@richardkeit the problem is the 4 dynamodb tables dont exist, well it exists during the stack creation but will then be reverted/destroyed when the stack failed which will happen eventually
