### ISSUE TITLE
As of LZA v 1.7.0 having a forward slash in OU name now breaks LZA with an error

### ISSUE THREAD

**Issue by anthony-sarkis-pwc** [awslabs/landing-zone-accelerator-on-aws#472]
**Describe the bug**
If you have a / in an OU name LZA will error out in the pipeline, this is the error you will receive
<html>
<body>

2024-06-05 02:27:22.906 \| error \| runner \| Parent organizational unit "CI" not found for organizational unit "CI/CD" in AWS Organizations.
--
174 | Error: Parent organizational unit "CI" not found for organizational unit "CI/CD" in AWS Organizations.
175 | at AWSOrganization.manageOuCreation (/codebuild/output/src1517/src/s3/00/source/packages/@aws-accelerator/modules/lib/aws-organization/index.ts:337:17)
176 | at processTicksAndRejections (node:internal/process/task_queues:95:5)
177 | at async AWSOrganization.handler (/codebuild/output/src1517/src/s3/00/source/packages/@aws-accelerator/modules/lib/aws-organization/index.ts:200:7)
178 | at async main (/codebuild/output/src1517/src/s3/00/source/packages/@aws-accelerator/modules/bin/runner.ts:73:10)
179 | at async /codebuild/output/src1517/src/s3/00/source/packages/@aws-accelerator/modules/bin/runner.ts:81:20 {
180 | level: 'error',
181 | mainLabel: 'accelerator',
182 | [Symbol(level)]: 'error'
183 | }
184 | error Command failed with exit code 1.
185 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

</body>
</html>

**To Reproduce**
Add a / in an OU and be sure to include it in the organization-config.yaml file and run it on LZA v 1.7.0, previous versions work fine

**Expected behavior**
In previous LZA versions there was no issues, now it is erroring out stating it cannot find the OU.

**Please complete the following information about the solution:**

- [ ] Version: v1.7.0
- [ ] Region: us-east-1
- [ ] Was the solution modified from the version published on this repository? No
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? Yes
- [ ] Were there any errors in the CloudWatch Logs? Yes

**Screenshots**
Attached

**Additional context**
This has worked in every version of LZA, only v1.7.0 has this become an issue

**Comment by crissupb** [comment]
Please ensure that you also have the "CI" OU defined separately in the config file along with "CI/CD".  The error indicates that it may be missing.  The "CD" OU is a child of the "CI" OU when there are slashes in the name.

**Comment by fdjahnke** [comment]
Hello @anthony-sarkis-pwc, thank you again for reporting this, and for your patience.

Here is a summary of what we found:

- A `/` in an OU name is treated as a nested OU - `CI/CD` means an OU named `CD` under a parent OU named `CI`. Forward-slash (nested) OUs are supported; the slash itself does not break LZA.
- Starting in v1.7.0, each level of the hierarchy must be declared in `organization-config.yaml`, so the parent must be listed in addition to the child. LZA creates parents before children when both are declared:

```
organizationalUnits:
  - name: CI
  - name: CI/CD
```

- The error `Parent organizational unit "CI" not found` means the parent `CI` OU was not declared (or did not already exist in AWS Organizations). This is working as designed - LZA does not auto-create an undeclared parent.

This issue was originally reported on v1.7.0, which is now several releases behind. Since it has been open for a long time and the behavior works as designed in current LZA, we are going to close it as stale. If you upgrade to the current LZA version and still hit this with every level of the hierarchy declared, please re-open with your full `organizationalUnits` block and the LZA version, and we will be glad to take another look.

Thanks for supporting Landing Zone Accelerator!
