### ISSUE TITLE
Support CloudFormation templates with length greater than 51200 for customizations-config.yaml

### ISSUE THREAD

**Issue by atfurman** [awslabs/landing-zone-accelerator-on-aws#51]
**Is your feature request related to a problem? Please describe.**
When attempting to utilize `customizations-config.yaml` in version 1.3 to deploy our own CloudFormation stackSets, we are running into an error where the max template length supported appears to be 51200 bytes:

```
❌  AWSAccelerator-CustomizationsStack-246440944109-us-gov-west-1 failed: Error: The stack named AWSAccelerator-CustomizationsStack-246440944109-us-gov-west-1 failed to deploy: UPDATE_ROLLBACK_COMPLETE: Properties validation failed for resource AwsAcceleratorCustomAtomAwsAlerts with message:
--
#: #: only 1 subschema matches out of 2
#/TemplateBody: expected maxLength: 51200, actual: 94352, Resource handler returned message: "Operation 48a37db6-9c54-4555-be7a-efab2919886d on StackSet arn:aws-us-gov:cloudformation:us-gov-west-1:246440944109:stackset/ATOM-ThreatAlert-Scan-Role:8c356590-8c2f-4eb9-862c-8c91fa33996c is in progress (Service: CloudFormation, Status Code: 409, Request ID: d1db2c0b-511e-4f35-bc5f-68e9b0a17312)" (RequestToken: a79de482-54bd-9749-7e40-b7def9645bd6, HandlerErrorCode: GeneralServiceException)
at FullCloudFormationDeployment.monitorDeployment (/codebuild/output/src190/src/s3/00/source/node_modules/aws-cdk/lib/api/deploy-stack.ts:496:13)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async deployStack (/codebuild/output/src190/src/s3/00/source/node_modules/aws-cdk/lib/cdk-toolkit.ts:241:24)
at async /codebuild/output/src190/src/s3/00/source/node_modules/aws-cdk/lib/deploy.ts:39:11
at async run (/codebuild/output/src190/src/s3/00/source/node_modules/p-queue/dist/index.js:163:29)
 
❌ Deployment failed: Error: Stack Deployments Failed: Error: The stack named AWSAccelerator-CustomizationsStack-246440944109-us-gov-west-1 failed to deploy: UPDATE_ROLLBACK_COMPLETE: Properties validation failed for resource AwsAcceleratorCustomAtomAwsAlerts with message:
#: #: only 1 subschema matches out of 2
#/TemplateBody: expected maxLength: 51200, actual: 94352, Resource handler returned message: "Operation 48a37db6-9c54-4555-be7a-efab2919886d on StackSet arn:aws-us-gov:cloudformation:us-gov-west-1:246440944109:stackset/ATOM-ThreatAlert-Scan-Role:8c356590-8c2f-4eb9-862c-8c91fa33996c is in progress (Service: CloudFormation, Status Code: 409, Request ID: d1db2c0b-511e-4f35-bc5f-68e9b0a17312)" (RequestToken: a79de482-54bd-9749-7e40-b7def9645bd6, HandlerErrorCode: GeneralServiceException)
at Object.exports.deployStacks (/codebuild/output/src190/src/s3/00/source/node_modules/aws-cdk/lib/deploy.ts:61:11)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async CdkToolkit.deploy (/codebuild/output/src190/src/s3/00/source/node_modules/aws-cdk/lib/cdk-toolkit.ts:314:7)
at async Function.execute (/codebuild/output/src190/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/toolkit.ts:281:9)
at async Promise.all (index 0)
at async Function.run (/codebuild/output/src190/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/accelerator.ts:464:5)
Stack Deployments Failed: Error: The stack named AWSAccelerator-CustomizationsStack-246440944109-us-gov-west-1 failed to deploy: UPDATE_ROLLBACK_COMPLETE: Properties validation failed for resource AwsAcceleratorCustomAtomAwsAlerts with message:
#: #: only 1 subschema matches out of 2
#/TemplateBody: expected maxLength: 51200, actual: 94352, Resource handler returned message: "Operation 48a37db6-9c54-4555-be7a-efab2919886d on StackSet arn:aws-us-gov:cloudformation:us-gov-west-1:246440944109:stackset/ATOM-ThreatAlert-Scan-Role:8c356590-8c2f-4eb9-862c-8c91fa33996c is in progress (Service: CloudFormation, Status Code: 409, Request ID: d1db2c0b-511e-4f35-bc5f-68e9b0a17312)" (RequestToken: a79de482-54bd-9749-7e40-b7def9645bd6, HandlerErrorCode: GeneralServiceException)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 
[Container] 2023/01/26 18:09:50 Command did not exit successfully yarn run ts-node --transpile-only cdk.ts --require-approval never $CDK_OPTIONS --config-dir $CODEBUILD_SRC_DIR_Config --partition aws-us-gov --app cdk.out exit status 1
[Container] 2023/01/26 18:09:50 Phase complete: BUILD State: FAILED
[Container] 2023/01/26 18:09:50 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: yarn run ts-node --transpile-only cdk.ts --require-approval never $CDK_OPTIONS --config-dir $CODEBUILD_SRC_DIR_Config --partition aws-us-gov --app cdk.out. Reason: exit status 1
[Container] 2023/01/26 18:09:51 Entering phase POST_BUILD
[Container] 2023/01/26 18:09:51 Phase complete: POST_BUILD State: SUCCEEDED
[Container] 2023/01/26 18:09:51 Phase context status code:  Message:
```

**Describe the feature you'd like**

While we can refactor our post-deployment stacks to be smaller than this limit, it would be helpful if the limitations were the same as the CloudFormation service itself, or if at the very least these limitations were explicitly documented in https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.CustomizationConfig.html 

**Additional context**

**Comment by atfurman** [comment]
@rgd11 would it be possible to have a member of the team provide some input and context on this issue? Is this a limit which can be easily changed in the short term, or should we proceed with reworking our post-deployment stacks to work within these constraints?

**Comment by erwaxler** [comment]
@atfurman Thank you for identifying this! This issue can and will be addressed in a future release, an internal ticket has been created to track the work. The change will require uploading custom stack templates to S3 before deployment. 

In terms of your best steps moving forward, it depends on your timeline. I expect this work to be implemented in an upcoming minor release within in the next few months. If your implementation timeline is days or weeks rather than months, I would recommend reworking your stacks into smaller templates to continue moving forward. I will keep this issue updated with any new information.

**Comment by atfurman** [comment]
Thanks @erwaxler. If this is likely to take a few months we will refactor as an interim move, and plan to re-consolidate once larger templates are supported.

**Comment by erwaxler** [comment]
@atfurman After looking into this further, the team has been able to implement a fix for this issue. We expect to include this in our upcoming v1.3.1 release. This release is still a few weeks away, but I wanted to update you in case this new timeline changes your approach.

**Comment by johnraws** [comment]
@atfurman the newest release of v1.3.2 includes the ability to manage large AWS CloudFormation templates, specifically in the commit https://github.com/awslabs/landing-zone-accelerator-on-aws/commit/15315d575d8a416f78d67401899609379e6dd6db
