### ISSUE TITLE
Network-Association error when deploying third party firewall

### ISSUE THREAD

**Issue by jonathan-pehau** [awslabs/landing-zone-accelerator-on-aws#547]
Good day,

When deploying the LZA with a 3rd party Firewall, in our case Fortigates, we have found a problem with the deployment using the S3 repository for the code rather than CodeCommit.

In our customization-config.yaml file, we are defining the configFile and licenseFile path. 

Customization-config.yaml:
> firewalls:
>   instances:
>     - name: *Firewall_Name_A
>       vpc: *Shared_VPC
>       configFile: fortigate/config-a.txt
>       licenseFile: fortigate/license-a.lic

**Before version 1.9.x**
Previously with the CodeCommit repo in previous version, the pipeline copied the files from the repo into the created bucket _aws-accelerator-assets-xxxxxxxxxxx-ca-central-1_ . 

When reaching the NetworkAssociation step in the pipeline, the code was copying the files from the bucket _aws-accelerator-assets-xxxxxxxxxxx-ca-central-1_ into a bucket hosted in the account that will deploy the Firewalls.

**In version 1.9.x**
No files are copied into the bucket _aws-accelerator-assets-xxxxxxxxxxx-ca-central-1_ when running the pipeline, giving the error at stage Network_Association of "Error: NoSuchKey: The specified key does not exist."

Complete error:
2024-08-22T13:58:23.116Z	27fcd1f5-40a9-4ad8-954d-18eadbb93d51	ERROR	Invoke Error 	{
    "errorType": "Error",
    "errorMessage": "NoSuchKey: The specified key does not exist.",
    "stack": [
        "Error: NoSuchKey: The specified key does not exist.",
        "    at WTr (/var/task/index.js:36:323624)",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
        "    at async Runtime.HTr [as handler] (/var/task/index.js:36:322619)"
    ]
}

**Workaround**
We  copied the files manually in the bucket _aws-accelerator-assets-xxxxxxxxxxx-ca-central-1_ and then the pipeline deployed correctly the entire stack

**Expected behavior**
Files defined in the customization-config.yaml copied from the repo (.ZIP) into the bucket _aws-accelerator-assets-xxxxxxxxxxx-ca-central-1_ during the pipeline deployment

- [ ] Version: 1.9.1
- [ ] Region: ca-central-1

**Comment by fdjahnke** [comment]
Hello @jonathan-pehau, thanks for filing this with the Landing Zone Accelerator team!

This isn't a regression — LZA has never auto-copied firewall `configFile` / `configDir` / `licenseFile` from the config repository into the assets bucket, in any source mode. The custom resource that processes these reads directly from `${AcceleratorPrefix}-assets`, which is why you see `NoSuchKey` when the file isn't there. The TypeDoc reference for [[Ec2FirewallInstanceConfig](https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/typedocs/interfaces/packages__aws-accelerator_config_lib_models_customizations-config.IEc2FirewallInstanceConfig.html)](https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/typedocs/interfaces/packages__aws-accelerator_config_lib_models_customizations-config.IEc2FirewallInstanceConfig.html) and [[Ec2FirewallAutoScalingGroupConfig](https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/typedocs/interfaces/packages__aws-accelerator_config_lib_models_customizations-config.IEc2FirewallAutoScalingGroupConfig.html)](https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/typedocs/interfaces/packages__aws-accelerator_config_lib_models_customizations-config.IEc2FirewallAutoScalingGroupConfig.html) has stated this for some time:

> The license file must be uploaded to the accelerator-created assets bucket in the home region of your Management account. This is the `${AcceleratorPrefix}-assets` bucket, not the `cdk-accel-assets` bucket.

If v1.8.x with CodeCommit appeared to copy the files for you, that was incidental to your repo layout, not LZA behavior. Your manual upload is the documented procedure.

Closing as not-a-bug. The S3 source-code [[doc page](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/source-code-location.html)](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/source-code-location.html) doesn't currently call this out — opening a separate doc-only update to make the requirement more discoverable. Reopen and ping me if you have questions.
