### ISSUE TITLE
Clarity on opt-in regions for individual account

### ISSUE THREAD

**Issue by gr-georgeshort** [awslabs/landing-zone-accelerator-on-aws#563]
**Describe the bug**
We are looking to enable an opt-in region for a single account. When reading https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/opt-in-regions.html it states "Allow your desired opt-in AWS Regions for all accounts" but then only mentions enabling within the management, log archive and audit accounts.

When attempting to run LZA, it is failing within the Bootstrap stage due to trying to deploy a stack within the region in each account. Is it expected that we have to enable the region for every account managed by LZA?

**Comment by snemir2** [comment]
similar problem? 
I get the following when trying to enable us-east-1 region
```
❌ Deployment failed: Error: AWSAccelerator-KeyStack-xxx-us-east-1: This CDK deployment requires bootstrap stack version '6', but during the confirmation via SSM parameter /cdk-bootstrap/accel/version the following error occurred: AccessDeniedException: User: arn:aws:sts::xxx:assumed-role/cdk-accel-deploy-role-xxxus-east-1/aws-cdk-root is not authorized to perform: ssm:GetParameter on resource: arn:aws:ssm:us-east-1:xxx:parameter/cdk-bootstrap/accel/version with an explicit deny in a service control policy
--
494 | at Deployments.validateBootstrapStackVersion (/codebuild/output/src3599/src/s3/00/source/node_modules/aws-cdk/lib/api/deployments.ts:665:13)
495 | at processTicksAndRejections (node:internal/process/task_queues:95:5)
496 | at async Deployments.buildSingleAsset (/codebuild/output/src3599/src/s3/00/source/node_modules/aws-cdk/lib/api/deployments.ts:614:5)
497 | at async Object.buildAsset (/codebuild/output/src3599/src/s3/00/source/node_modules/aws-cdk/lib/cdk-toolkit.ts:254:7)
498 | at async /codebuild/output/src3599/src/s3/00/source/node_modules/aws-cdk/lib/util/work-graph.ts:108:11
499 | 2024-11-19 18:08:01.947 \| error \| toolkit \| AWSAccelerator-KeyStack-288761734645-us-east-1: This CDK deployment requires bootstrap stack version '6', but during the confirmation via SSM parameter /cdk-bootstrap/accel/version the following error occurred: AccessDeniedException: User: arn:aws:sts::xxx:assumed-role/cdk-accel-deploy-role-xxx-us-east-1/aws-cdk-root is not authorized to perform: ssm:GetParameter on resource: arn:aws:ssm:us-east-1:xxx:parameter/cdk-bootstrap/accel/version with an explicit deny in a service control policy
500 | Deployment failed
501 | error Command failed with exit code 1.
502 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by fdjahnke** [comment]
Hello @gr-georgeshort, thanks for filing this with the Landing Zone Accelerator team!

Resolved in **v1.10.0**. Set the following in `global-config.yaml`:

```yaml
enableOptInRegions: true
```

The accounts stage will then call `account:EnableRegion` per managed account before bootstrap runs, so `AWSControlTowerExecution` no longer fails on the not-yet-opted-in region. Account opt-in is per-account at the AWS API level ([[EnableRegion](https://docs.aws.amazon.com/accounts/latest/reference/API_EnableRegion.html)](https://docs.aws.amazon.com/accounts/latest/reference/API_EnableRegion.html)) — Control Tower governing a region does not opt member accounts in.

Closing as resolved. Doc page update is tracked separately. Reopen and ping me if you hit issues after upgrading.
