### ISSUE TITLE
Sub OUs not deploying as expected, failure at Prepare stage

### ISSUE THREAD

**Issue by Godtrilla** [awslabs/landing-zone-accelerator-on-aws#570]
**Describe the bug**
Creating SUB-OUs seems to fail.  Parent OU already exists.  Attempting to create sub-OUs under the parent OU.  As pictured in LZA config.  

The following OUs were already deployed: 
organizationalUnits:
--
 - name: Architecture
 - name: Security
 - name: Infrastructure
 - name: Sandbox
 - name: PlatformEngineering
 - name: PlatformEngineering/Prod
 - name: PlatformEngineering/Dev
 - name ResearchEngineering
 - name: ResearchEngineering/Prod
 - name: ResearchEngineering/Dev
 - name: ResearchEngineering/Colo
 - name: ResearchEngineering/Colo/Prod
 - name: ResearchEngineering/Colo/Dev
 - name: Vendor

Attempting to create: 

 - name: Architecture/Prod
 - name: Architecture/Dev
 - name: Architecture/Sandbox

Pipeline stage failure: Prepare stage

**To Reproduce**
Steps to reproduce the behavior.

Deploy multiple OUs with sub OUs via LZA config. 

Run LZA Pipeline and an error occurs. 

Remove those same OUs and that solves the error but unable to deploy new sub-OUs

**Expected behavior**
The expected behavior is that new sub-OUs are deployed via the LZA config.  The code-pipeline is started and the OUs are deployed via the code-pipeline. 

**Please complete the following information about the solution:**

- [ ] Version: v1.9.1

> To get the version of the solution, you can look at the description of the created AWS CloudFormation stack used to install the LZA (AWSAccelerator-InstallerStack). For example, "__(SO0199) Landing Zone Accelerator on AWS. **Version 1.5.1.**__". If the description does not contain the version information, you can look at the Parameters of the stack for the **RepositoryBranchName** as that should contain the version number.

- [ ] Region: [eu-east-1]
- [ ] Was the solution modified from the version published on this repository? No.
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? Yes.
- [ ] Were there any errors in the CloudWatch Logs? Errors are in codepipeline, pictured below. 

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).
![screenshot_image](https://github.com/user-attachments/assets/232749db-43cc-487f-b443-27bae545ee7e)

**Additional context**

**Comment by turqual** [comment]
We manually recreated the OUs and had the pipeline register them with control tower. Now we are getting the following error in the prepare stage...


```
2024-09-16 16:59:52.681 | info | index | The organization unit "Architecture/Sandbox" already exists in AWS Organizations, create organizational operation skipped.
2024-09-16 16:59:52.922 | info | index | The organizational unit "Architecture/Sandbox" is not registered into AWS Control Tower, it will be registered now.
2024-09-16 17:00:00.591 | info | index | Enabling baseline for "Organizational Unit "Sandbox" with id "ou-yyax-*****mz7" for parent "Architecture". Baseline version is "4.0" and baseline identifier is "arn:aws:controltower:eu-west-1::baseline/17BSJV3IGJ2*****".
2024-09-16 17:00:01.182 | error | runner | This baseline is already enabled on this target. To resolve any enablement failures or drift, call ResetEnabledBaseline. To update the baseline version or parameters, call UpdateEnabledBaseline.
ValidationException: This baseline is already enabled on this target. To resolve any enablement failures or drift, call ResetEnabledBaseline. To update the baseline version or parameters, call UpdateEnabledBaseline.
    at de_ValidationExceptionRes (/codebuild/output/src1540/src/s3/00/source/node_modules/@aws-sdk/client-controltower/dist-cjs/index.js:1298:21)
    at de_CommandError (/codebuild/output/src1540/src/s3/00/source/node_modules/@aws-sdk/client-controltower/dist-cjs/index.js:1192:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /codebuild/output/src1540/src/s3/00/source/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
    at async /codebuild/output/src1540/src/s3/00/source/node_modules/@smithy/core/dist-cjs/index.js:165:18
    at async /codebuild/output/src1540/src/s3/00/source/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
    at async /codebuild/output/src1540/src/s3/00/source/node_modules/@aws-sdk/client-controltower/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:33:22 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: 'c5387b70-7932-46ba-a27c-c8f2a39f1322',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  level: 'error',
  mainLabel: 'accelerator',
  [Symbol(level)]: 'error'
}
error Command failed with exit code 1.
```

**Comment by fdjahnke** [comment]
Hello @Godtrilla, thank you for filing this issue. The behavior you and @turqual hit on v1.9.1 - the Prepare stage calling EnableBaseline on an OU whose Control Tower baseline was already enabled and failing with "This baseline is already enabled on this target" - has since been resolved. OU registration into Control Tower was reworked to first check the enabled baselines and only enable when the OU is not already registered, routing already-enabled OUs to an update/skip path instead.

This is fixed in current releases (latest v1.15.5). Please upgrade and re-run the pipeline. If you still see a Prepare-stage failure on the latest version, re-open with the CloudWatch log error text (not just a screenshot) and your `controlTower`/`organizationalUnits` config and we will take another look. Closing as resolved.
