### ISSUE TITLE
bug: Replacements not working for regions

### ISSUE THREAD

**Issue by mbevc1** [awslabs/landing-zone-accelerator-on-aws#594]
**Describe the bug**
When trying to use global replacement in customisations I've noticed if used in `regions` field it passes validation, but deployment fails!

**To Reproduce**
* create global replacement, e.g. `HomeRegion`
* use it in the regions value in customisations:
```
customizations:
  cloudFormationStackSets:
    - name: Test1
      description: Enables Test1 IAM Role
      regions:
        - {{ HomeRegion }}
      capabilities: [CAPABILITY_IAM, CAPABILITY_NAMED_IAM, CAPABILITY_AUTO_EXPAND]
...
```
* validation passes, synth passes but deployment fails

**Expected behavior**

**Please complete the following information about the solution:**

- [x] Version: [v1.9.2]

> To get the version of the solution, you can look at the description of the created AWS CloudFormation stack used to install the LZA (AWSAccelerator-InstallerStack). For example, "__(SO0199) Landing Zone Accelerator on AWS. **Version 1.5.1.**__". If the description does not contain the version information, you can look at the Parameters of the stack for the **RepositoryBranchName** as that should contain the version number.

- [x] Region: [e.g. eu-west-1]
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by thorben-akent** [comment]
Also ran into this, but for [enabledRegions](https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/typedocs/latest/interfaces/___packages__aws_accelerator_config_lib_models_global_config.IGlobalConfig.html#enabledRegions) in the global config.

replacements-config.yaml:
```
globalReplacements:
  - key: HomeRegion
    type: String
    value: us-east-1
```

global-config.yaml:
```
homeRegion: "{{ HomeRegion }}"
enabledRegions:
  - "{{ HomeRegion }}"
```

Resulting error:
```
$ ts-node ./packages/@aws-accelerator/accelerator/lib/config-validator.ts /lza/config/
2025-03-24 20:00:53.145 | error | accelerator | Could not parse content in global-config:
* /enabledRegions/0 => must be equal to one of the allowed values (af-south-1,ap-east-1,ap-northeast-1,ap-northeast-2,ap-northeast-3,ap-south-1,ap-south-2,ap-southeast-1,ap-southeast-2,ap-southeast-3,ap-southeast-4,ca-central-1,ca-west-1,cn-north-1,cn-northwest-1,eu-central-1,eu-central-2,eu-north-1,eu-south-1,eu-south-2,eu-west-1,eu-west-2,eu-west-3,il-central-1,me-central-1,me-south-1,sa-east-1,us-east-1,us-east-2,us-gov-west-1,us-gov-east-1,us-iso-east-1,us-isob-east-1,us-iso-west-1,us-west-1,us-west-2)
/lza/source/packages/@aws-accelerator/accelerator/lib/accelerator.js:63
    throw new Error('Synthesis failed');
    ^
Error: Synthesis failed
    at process.<anonymous> (/lza/source/packages/@aws-accelerator/accelerator/lib/accelerator.ts:93:9)
    at process.emit (node:events:526:35)
    at process.emit (node:domain:488:12)
    at process.emit.sharedData.processEmitHook.installedValue [as emit] (/lza/source/node_modules/@cspotcode/source-map-support/source-map-support.js:745:40)
    at process._fatalException (node:internal/process/execution:178:25)
```

**Comment by erwaxler** [comment]
Hi @mbevc1 I'm pleased to say this is now possible in LZA v1.13.1! Please see the Universal Configuration for an example of how to use a `StringList` replacement for `enabledRegions`: https://github.com/aws/lza-universal-configuration/blob/main/modules/base/default/global-config.yaml

Thank you for your continued support of the LZA!
