### ISSUE TITLE
Comma Delimited parameters in custom-config cause array.some error in bootstrap stage.

### ISSUE THREAD

**Issue by bfg-cloudsupport** [awslabs/landing-zone-accelerator-on-aws#599]
**Describe the bug**
Passing a parameter string to a parameter of comma delimited type in a CloudFormationStack in custom-config causes a failure in the Bootstrap stage.

**To Reproduce**
Deploy a cloudformation stack with a comma delimited parameter type. Pass a string to the parameter in customizations-config.yaml (e.g. Value: 'foo,bar')

**Expected behavior**
String is passed to CreateStack parameter which accepts and parses it as comma delimited type. Stack deploys.

**Please complete the following information about the solution:**

- [ 1.9.2] Version: [e.g. v1.5.1]

> To get the version of the solution, you can look at the description of the created AWS CloudFormation stack used to install the LZA (AWSAccelerator-InstallerStack). For example, "__(SO0199) Landing Zone Accelerator on AWS. **Version 1.5.1.**__". If the description does not contain the version information, you can look at the Parameters of the stack for the **RepositoryBranchName** as that should contain the version number.

- [ ap-southeast-2] Region: [e.g. us-east-1]
- [No ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [Yes ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

`2024-10-09 01:32:32.388 | error | toolkit | array.some is not a function
2024-10-09 01:32:32.393 | error | accelerator | Runtime Error
/codebuild/output/src3391/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/accelerator.ts:63
    throw new Error('Synthesis failed');
    ^
Error: Synthesis failed
    at process.<anonymous> (/codebuild/output/src3391/src/s3/00/source/packages/@aws-accelerator/accelerator/lib/accelerator.ts:93:9)
    at process.emit (node:events:529:35)
    at process.emit (node:domain:489:12)
    at process.emit.sharedData.processEmitHook.installedValue [as emit] (/codebuild/output/src3391/src/s3/00/source/node_modules/@cspotcode/source-map-support/source-map-support.js:745:40)
    at process._fatalException (node:internal/process/execution:169:25)`

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by richardkeit** [comment]
[Instance Scheduler on AWS](https://docs.aws.amazon.com/solutions/latest/instance-scheduler-on-aws/step-1-launch-the-instance-scheduler-hub-stack.html) as an example where comma delimited parameters are used

**Comment by king-millez** [comment]
Bump.

**Comment by richardkeit** [comment]
@anthony-okros - as this is an older issues, what version of the LZA are you still experiencing this issue?

**Comment by anthony-okros** [comment]
Hey @richardkeit - currently experiencing on `1.12.2`. We've gone ahead with a workaround (using `!Split` against string data types instead).

**Comment by florian-netlight** [comment]
Looks like the issue is still present in 1.13.0

**Comment by fdjahnke** [comment]
Hello @bfg-cloudsupport, thank you for filing this with the Landing Zone Accelerator team, and thanks to everyone who added context.

There is a supported way to do this today. CloudFormation `CommaDelimitedList` parameters expect an array, but the customizations-config parameter `value` is a single string, which is what triggers the `array.some is not a function` error at synth. Instead, define the parameter in your template as a `String` type and use the `!Split` intrinsic function to turn the comma-separated string into a list where it's consumed. For example:

```yaml
Parameters:
  SubnetIds:
    Type: String          # not CommaDelimitedList
Resources:
  MyResource:
    Properties:
      SubnetIds: !Split [",", !Ref SubnetIds]
```

You then pass the value as a plain comma-separated string (e.g. `value: 'subnet-aaa,subnet-bbb'`) in customizations-config.yaml. This produces the same list behavior the template needs.

Since there's a working approach available, we're closing this issue. Please feel free to follow up if anything is unclear - just ping me so I'll see it. Thanks for supporting Landing Zone Accelerator!
