### ISSUE TITLE
Logging stack is trying to assume the `managementAccountAccessRole` for deployments within the Management account

### ISSUE THREAD

**Issue by kisst** [awslabs/landing-zone-accelerator-on-aws#603]
**Describe the bug**
```
❌ Deployment failed: AccessDenied: User: arn:aws:sts::<managmentaccountid>:assumed-role/AWSAccelerator-PipelineSt-AdminCdkToolkitRole292E16-UniqRandomStr/AWSCodeBuild-ec87b680-634e-4429-9aa5-252d3350e8a9 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::<managmentaccountid>:role/OrganizationAccountAccessRole
    at Request.extractError (/codebuild/output/src331/src/s3/00/source/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/codebuild/output/src331/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/codebuild/output/src331/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/codebuild/output/src331/src/s3/00/source/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/codebuild/output/src331/src/s3/00/source/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/codebuild/output/src331/src/s3/00/source/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /codebuild/output/src331/src/s3/00/source/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/codebuild/output/src331/src/s3/00/source/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/codebuild/output/src331/src/s3/00/source/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/codebuild/output/src331/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'AccessDenied',
  time: 2024-10-11T03:53:55.657Z,
  requestId: '1243baf1-01f5-45fe-b748-a2d27c88cae4',
  statusCode: 403,
  retryable: false,
  retryDelay: 96.37077033090154
}
2024-10-11 03:53:55.659 | error | toolkit | User: arn:aws:sts::<managmentaccountid>:assumed-role/AWSAccelerator-PipelineSt-AdminCdkToolkitRole292E16-UniqRandomStr/AWSCodeBuild-ec87b680-634e-4429-9aa5-252d3350e8a9 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::<managmentaccountid>:role/OrganizationAccountAccessRole
Deployment failed
error Command failed with exit code 1.
```
As per the above error message, for some reason the deployment of the Logging stack running within the management account itself, is trying to use the `managementAccountAccessRole` within the account 

**To Reproduce**
Unsure what's changed, rebuild it with an older version of the config zip ( one which run before ) and it failed this time, no changes in the account, or in the config.

**Please complete the following information about the solution:**

- [x] Version: 1.9.2
- [x] Region: us-east-1
- [x] Was the solution modified from the version published on this repository: No
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses: Yes
- [x] Were there any errors in the CloudWatch Logs: See above

**Additional context**
After a full pipeline run, made a single line change in iam, tried to deploy it, but it failed on logging, so after reading the logs, I tried rolling back the config change, and rebuild, but it still failed.

**Comment by JimToupet** [comment]
Are you using Control Tower ?

If so, you have to set this in `global-config.yaml`

`managementAccountAccessRole: AWSControlTowerExecution # UPDATE: If using Control Tower, set to AWSControlTowerExecution`

And set the useManagementAccessRole to true:

```
cdkOptions:
  useManagementAccessRole: true
  customDeploymentRole: AWSAccelerator-PipelineRole # UPDATE: If using a custom AcceleratorPrefix in the installer stack, this need to be updated accordingly
```

**Comment by kisst** [comment]
No Control Tower, in use in this install in the meantime I opened a support ticket within the effected AWS account as well, where the workaround suggested by the support was to create this Org role in the Master account too by hand while the fix is being worked on, as apparently this error is observed in other installations too..

**Comment by Athanasii** [comment]
If not using control tower, you must create an organization and ensure these [mandatory accounts](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/mandatory-accounts.html) are present.

**Comment by florianbeisel** [comment]
The issue @schnipseljagd describes is happening in an environment where we are using control tower but ran into this issue nonetheless. 

We would kindly ask you to reopen this issue.
