### ISSUE TITLE
Using LZA to add SCP causes S3 error: Access Denied

### ISSUE THREAD

**Issue by andreprawira** [awslabs/landing-zone-accelerator-on-aws#669]
**Describe the bug**
im using aws lza to deploy SCPs to my organization, ive been adding several SCPS and the pipeline works just fine no problem, until i add an SCP that is supposed to enable encryption on S3 bucket, however once i added it the Network_Prepare, Security, Operations boxes in Deploy stage fail with the same error, here i the build log

```
AWSAccelerator-NetworkPrepStack-<the account where i deploy the SCP to>-us-east-1 failed: Error [ValidationError]: S3 error: Access Denied
--
451 | For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html
452 | at Request.extractError (/codebuild/output/src3727/src/s3/00/source/node_modules/aws-sdk/lib/protocol/query.js:50:29)
453 | at Request.callListeners (/codebuild/output/src3727/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
454 | at Request.emit (/codebuild/output/src3727/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
455 | at Request.emit (/codebuild/output/src3727/src/s3/00/source/node_modules/aws-sdk/lib/request.js:686:14)
456 | at Request.transition (/codebuild/output/src3727/src/s3/00/source/node_modules/aws-sdk/lib/request.js:22:10)
457 | at AcceptorStateMachine.runTo (/codebuild/output/src3727/src/s3/00/source/node_modules/aws-sdk/lib/state_machine.js:14:12)
458 | at /codebuild/output/src3727/src/s3/00/source/node_modules/aws-sdk/lib/state_machine.js:26:10
459 | at Request.<anonymous> (/codebuild/output/src3727/src/s3/00/source/node_modules/aws-sdk/lib/request.js:38:9)
460 | at Request.<anonymous> (/codebuild/output/src3727/src/s3/00/source/node_modules/aws-sdk/lib/request.js:688:12)
461 | at Request.callListeners (/codebuild/output/src3727/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
462 | code: 'ValidationError',
463 | time: 2024-12-05T02:14:21.798Z,
464 | requestId: '50884d1d-5784-4a3d-9d0c-a89c32a44745',
465 | statusCode: 400,
466 | retryable: false,
467 | retryDelay: 847.8408279645436
468 | }
469 |  
470 | ❌ Deployment failed: Error [ValidationError]: S3 error: Access Denied
471 | For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html
472 | at Request.extractError (/codebuild/output/src3727/src/s3/00/source/node_modules/aws-sdk/lib/protocol/query.js:50:29)
473 | at Request.callListeners (/codebuild/output/src3727/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
474 | at Request.emit (/codebuild/output/src3727/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
475 | at Request.emit (/codebuild/output/src3727/src/s3/00/source/node_modules/aws-sdk/lib/request.js:686:14)
476 | at Request.transition (/codebuild/output/src3727/src/s3/00/source/node_modules/aws-sdk/lib/request.js:22:10)
477 | at AcceptorStateMachine.runTo (/codebuild/output/src3727/src/s3/00/source/node_modules/aws-sdk/lib/state_machine.js:14:12)
478 | at /codebuild/output/src3727/src/s3/00/source/node_modules/aws-sdk/lib/state_machine.js:26:10
479 | at Request.<anonymous> (/codebuild/output/src3727/src/s3/00/source/node_modules/aws-sdk/lib/request.js:38:9)
480 | at Request.<anonymous> (/codebuild/output/src3727/src/s3/00/source/node_modules/aws-sdk/lib/request.js:688:12)
481 | at Request.callListeners (/codebuild/output/src3727/src/s3/00/source/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
482 | code: 'ValidationError',
483 | time: 2024-12-05T02:14:21.798Z,
484 | requestId: '50884d1d-5784-4a3d-9d0c-a89c32a44745',
485 | statusCode: 400,
486 | retryable: false,
487 | retryDelay: 847.8408279645436
488 | }
489 | 2024-12-05 02:14:21.801 \| error \| toolkit \| S3 error: Access Denied
```

i know this is a problem with an IAM role but i already added the IAM role of the pipeline itself and my own reserve sso ARNs but its still failing, i dont know if there is something that im missing

**To Reproduce**
This is the SCP that i use

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Deny",
      "Action": [
        "s3:PutObject",
        "s3:GetObject",
        "s3:ReplicateObject"
      ],
      "Resource": "*",
      "Condition": {
        "Null": {
          "s3:x-amz-server-side-encryption": "true"
        },
        "ArnNotLike": {
          "aws:PrincipalARN": [
            "arn:aws:iam::*:role/aws-reserved/sso.amazonaws.com/AWSReservedSSO_AdministratorAccess_*",
            "arn:aws:iam::*:role/AWSAccelerator-*",
            "arn:aws:iam::*:role/AWS-Landing-Zone-*",
            "arn:aws:iam::*:role/cdk-*",
            "arn:aws:iam::<my-management-account-id>:role/AWSAccelerator-PipelineSt-PipelinePipelineRole....."
          ]
        }
      }
    },
    {
      "Effect": "Deny",
      "Action": [
        "s3:PutObject",
        "s3:GetObject",
        "s3:ReplicateObject"
      ],
      "Resource": "*",
      "Condition": {
        "ForAllValues:StringNotEquals": {
          "s3:x-amz-server-side-encryption": [
            "AES256",
            "aws:kms"
          ]
        },
        "ArnNotLike": {
          "aws:PrincipalARN": [
            "arn:aws:iam::*:role/aws-reserved/sso.amazonaws.com/AWSReservedSSO_AdministratorAccess_*",
            "arn:aws:iam::*:role/AWSAccelerator-*",
            "arn:aws:iam::*:role/AWS-Landing-Zone-*",
            "arn:aws:iam::*:role/cdk-*",
            "arn:aws:iam::<my-management-account-id>:role/AWSAccelerator-PipelineSt-PipelinePipelineRole....."
          ]
        }
      }
    }
  ]
}
```

**Expected behavior**
pipeline should be working

**Please complete the following information about the solution:**

- [ ] Version: v1.10.0
- [ ] Region: e.g. us-east-1
- [ ] Was the solution modified from the version published on this repository? yes
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? yes, its got nothing to do with that
- [ ] Were there any errors in the CloudWatch Logs? yes, i posted the error

**Comment by richardkeit** [comment]
Using the sample configurations as inspiration:
https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/d8fe87d61cf8dc8fea255753bf93ffd24fae6d76/reference/sample-configurations/lza-sample-config/service-control-policies/guardrails-1.json#L18-L20

From the interpreted SCP, appear to be missing `MANAGEMENT_ACCOUNT_ACCESS_ROLE`

**Comment by andreprawira** [comment]
@richardkeit wow thank you, it works, you are the best!!
